import toggleLocation from './toggle-location';
import toggleAllLocations from './toggle-all-locations';
import setOnlyOneLocationPlusFalse from './set-only-one-location-plus-false';
import implantInverse from './implant-inverse';
import crownInverse from './crown-inverse';

export default {
    P01: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        locations: {},
        view: {
            coronaLingual: true,
            coronaTop: true,
            coronaLabial: true,
            root: true,
            gum: true,
        },
        setOnLoad: {},
    },
    P02: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        locations: {
            coronaLingualIncisalDistal: true,
            coronaLingualIncisalMiddle: true,
            coronaLingualIncisionMesial: true,
            coronaLingualMiddleDistal: true,
            coronaLingualMiddleMiddle: true,
            coronaLingualMiddleMesial: true,
            coronaLingualCervicalDistal: true,
            coronaLingualCervicalMiddle: true,
            coronaLingualCervicalMesial: true,
            coronaLabialIncisalDistal: true,
            coronaLabialIncisalMiddle: true,
            coronaLabialIncisionMesial: true,
            coronaLabialMiddleDistal: true,
            coronaLabialMiddleMiddle: true,
            coronaLabialMiddleMesial: true,
            coronaLabialCervicalDistal: true,
            coronaLabialCervicalMiddle: true,
            coronaLabialCervicalMesial: true,
            coronaTopBuccal: true,
            coronaTopMedial: true,
            coronaTopLingual: true,
            coronaTopDistal: true,
            coronaTopOclusial: true,
        },
        view: {
            coronaLingual: true,
            coronaLingualIncisalDistal: true,
            coronaLingualIncisalMiddle: true,
            coronaLingualIncisionMesial: true,
            coronaLingualMiddleDistal: true,
            coronaLingualMiddleMiddle: true,
            coronaLingualMiddleMesial: true,
            coronaLingualCervicalDistal: true,
            coronaLingualCervicalMiddle: true,
            coronaLingualCervicalMesial: true,
            coronaLabial: true,
            coronaLabialIncisalDistal: true,
            coronaLabialIncisalMiddle: true,
            coronaLabialIncisionMesial: true,
            coronaLabialMiddleDistal: true,
            coronaLabialMiddleMiddle: true,
            coronaLabialMiddleMesial: true,
            coronaLabialCervicalDistal: true,
            coronaLabialCervicalMiddle: true,
            coronaLabialCervicalMesial: true,
            coronaTopBuccal: true,
            coronaTopMedial: true,
            coronaTopLingual: true,
            coronaTopDistal: true,
            coronaTopOclusial: true,
            root: true,
            gum: true,
        },
        setOnLoad: {},
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
    },
    P03: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        locations: {
            silant: true,
        },
        view: {
            coronaLingual: true,
            coronaTop: true,
            coronaLabial: true,
            root: true,
            gum: true,
            silant: true,
        },
        setOnLoad: {
            silant: true,
        },
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
    },
    P04: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        locations: {},
        view: {
            coronaLingual: true,
            coronaTop: true,
            coronaLabial: true,
            root: true,
            gum: true,
        },
        setOnLoad: {},
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
    },
    P05: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        locations: {
            periodontit: true,
        },
        view: {
            coronaLingual: true,
            coronaTop: true,
            coronaLabial: true,
            root: true,
            gum: true,
            periodontit: true,
        },
        setOnLoad: {
            periodontit: true,
        },
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
    },
    P06: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        locations: {
            veneer: true,
        },
        view: {
            coronaLingual: true,
            coronaTop: true,
            coronaLabial: true,
            root: true,
            gum: true,
            veneer: true,
        },
        setOnLoad: {
            veneer: true,
        },
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
    },
    P07: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        locations: {
            rootCanal: true,
            periodontit: true,
        },
        view: {
            coronaLingual: true,
            coronaTop: true,
            coronaLabial: true,
            root: true,
            gum: true,
            rootCanal: true,
            periodontit: true,
        },
        setOnLoad: {
            rootCanal: true,
            periodontit: true,
        },
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
    },
    P08: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        locations: {
            gum: true,
        },
        view: {
            coronaLingual: true,
            coronaTop: true,
            coronaLabial: true,
            root: true,
            gum: true,
        },
        setOnLoad: {
            gum: true,
        },
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
    },
    P09: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        locations: {
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            silant: false,
        },
        view: {
            root: true,
            gum: true,
        },
        setOnLoad: {
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            silant: false,
        },
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
    },
    P10: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        locations: {
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMesial: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
            bridge: true,
            crown: true,
        },
        view: {
            crown: true,
            bridge: true,
            root: true,
            gum: true,
        },
        setOnLoad: {
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
            crown: true,
            bridge: true,
        },
        addLocation: (location, diagnose, originalDiagnose, toothId) => crownInverse(location, diagnose, originalDiagnose, toothId),
    },
    P11: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        locations: {
            coronaLingual: true,
            coronaTop: true,
            coronaLabial: true,
        },
        view: {
            coronaLingual: true,
            coronaTop: true,
            coronaLabial: true,
            root: true,
            gum: true,
        },
        setOnLoad: {
            coronaLingual: true,
            coronaTop: true,
            coronaLabial: true,
        },
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
    },
    P12: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        locations: {
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMesial: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
            bridge: true,
            crown: true,
        },
        view: {
            crown: true,
            bridge: true,
            root: true,
            gum: true,
        },
        setOnLoad: {
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
            crown: true,
            bridge: true,
        },
        addLocation: (location, diagnose, originalDiagnose, toothId) => crownInverse(location, diagnose, originalDiagnose, toothId),
    },
    P13: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        locations: {
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
            implant: true,
            crown: true,
            root: false,
            rootCanal: false,
            periodontit: false,

        },
        view: {
            crown: true,
            implant: true,
            gum: true,
            root: false,
            rootCanal: false,
            periodontit: false,
        },
        setOnLoad: {
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
            crown: true,
            implant: true,
            root: false,
            rootCanal: false,
            periodontit: false,

        },
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => implantInverse(location, diagnose, originalDiagnose, toothId),
    },
    P14: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {
            bone: true,
        },
        locations: {
            bone: true,
        },
        view: {
            bone: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
        },
    },
    P15: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {
            bone: true,
        },
        locations: {
            bone: true,

        },
        view: {
            bone: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
        },
    },
    P16: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        view: {},
        setOnLoad: {},
        addLocation: {},
    },
    P17: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        locations: {
            braces: true,
        },
        view: {
            coronaLingual: true,
            coronaTop: true,
            coronaLabial: true,
            root: true,
            gum: true,
            braces: true,
        },
        setOnLoad: {
            braces: true,
        },
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
    },
    P18: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {
            rootCanal: false,
            periodontit: false,
            silant: false,
            root: false,
            coronaLingual: false,
            coronaLabial: false,
            coronaTop: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
        },
        locations: {
            rootCanal: false,
            periodontit: false,
            silant: false,
            root: false,
            coronaLingual: false,
            coronaLabial: false,
            coronaTop: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
        },
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
        },
    },
    P19: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {
            bone: true,
            rootCanal: false,
            periodontit: false,
            silant: false,
            root: false,
            coronaLingual: false,
            coronaLabial: false,
            coronaTop: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
        },
        locations: {
            bone: true,
            rootCanal: false,
            periodontit: false,
            silant: false,
            root: false,
            coronaLingual: false,
            coronaLabial: false,
            coronaTop: false,
        },
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
            bone: true,
        },
    },
    P20: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {
            gum: true,
        },
        locations: {
            gum: true,
        },
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
        },
    },
    P21: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {
            root: false,
            coronaLingual: false,
            coronaLabial: false,
            coronaTop: false,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
        },
        locations: {
            root: false,
            rootCanal: false,
            periodontit: false,
            silant: false,
            coronaLingual: false,
            coronaLabial: false,
            coronaTop: false,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
        },
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
        },
    },
    P22: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        setOnLoad: {},
        locations: {},
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
        },
    },
    P23: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        setOnLoad: {},
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
        locations: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
        },
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
        },
    },
    P24: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        setOnLoad: {},
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
        locations: {
            coronaLingualIncisalDistal: true,
            coronaLingualIncisalMiddle: true,
            coronaLingualIncisionMesial: true,
            coronaLingualMiddleDistal: true,
            coronaLingualMiddleMiddle: true,
            coronaLingualMiddleMesial: true,
            coronaLingualCervicalDistal: true,
            coronaLingualCervicalMiddle: true,
            coronaLingualCervicalMesial: true,
            coronaLabialIncisalDistal: true,
            coronaLabialIncisalMiddle: true,
            coronaLabialIncisionMesial: true,
            coronaLabialMiddleDistal: true,
            coronaLabialMiddleMiddle: true,
            coronaLabialMiddleMesial: true,
            coronaLabialCervicalDistal: true,
            coronaLabialCervicalMiddle: true,
            coronaLabialCervicalMesial: true,
            coronaTopBuccal: true,
            coronaTopMedial: true,
            coronaTopLingual: true,
            coronaTopDistal: true,
            coronaTopOclusial: true,
        },
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
            coronaLingualIncisalDistal: true,
            coronaLingualIncisalMiddle: true,
            coronaLingualIncisionMesial: true,
            coronaLingualMiddleDistal: true,
            coronaLingualMiddleMiddle: true,
            coronaLingualMiddleMesial: true,
            coronaLingualCervicalDistal: true,
            coronaLingualCervicalMiddle: true,
            coronaLingualCervicalMesial: true,
            coronaLabialIncisalDistal: true,
            coronaLabialIncisalMiddle: true,
            coronaLabialIncisionMesial: true,
            coronaLabialMiddleDistal: true,
            coronaLabialMiddleMiddle: true,
            coronaLabialMiddleMesial: true,
            coronaLabialCervicalDistal: true,
            coronaLabialCervicalMiddle: true,
            coronaLabialCervicalMesial: true,
            coronaTopBuccal: true,
            coronaTopMedial: true,
            coronaTopLingual: true,
            coronaTopDistal: true,
            coronaTopOclusial: true,
        },
    },
    P25: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        setOnLoad: {},
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
        locations: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
        },
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
        },
    },
    P26: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
        locations: {},
        setOnLoad: {},
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
        },
    },
    P27: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {},
        locations: {
            root: true,
            coronaLingualIncisalDistal: true,
            coronaLingualIncisalMiddle: true,
            coronaLingualIncisionMesial: true,
            coronaLingualMiddleDistal: true,
            coronaLingualMiddleMiddle: true,
            coronaLingualMiddleMesial: true,
            coronaLingualCervicalDistal: true,
            coronaLingualCervicalMiddle: true,
            coronaLingualCervicalMesial: true,
            coronaLabialIncisalDistal: true,
            coronaLabialIncisalMiddle: true,
            coronaLabialIncisionMesial: true,
            coronaLabialMiddleDistal: true,
            coronaLabialMiddleMiddle: true,
            coronaLabialMiddleMesial: true,
            coronaLabialCervicalDistal: true,
            coronaLabialCervicalMiddle: true,
            coronaLabialCervicalMesial: true,
            coronaTopBuccal: true,
            coronaTopMedial: true,
            coronaTopLingual: true,
            coronaTopDistal: true,
            coronaTopOclusial: true,
        },
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
            coronaLingualIncisalDistal: true,
            coronaLingualIncisalMiddle: true,
            coronaLingualIncisionMesial: true,
            coronaLingualMiddleDistal: true,
            coronaLingualMiddleMiddle: true,
            coronaLingualMiddleMesial: true,
            coronaLingualCervicalDistal: true,
            coronaLingualCervicalMiddle: true,
            coronaLingualCervicalMesial: true,
            coronaLabialIncisalDistal: true,
            coronaLabialIncisalMiddle: true,
            coronaLabialIncisionMesial: true,
            coronaLabialMiddleDistal: true,
            coronaLabialMiddleMiddle: true,
            coronaLabialMiddleMesial: true,
            coronaLabialCervicalDistal: true,
            coronaLabialCervicalMiddle: true,
            coronaLabialCervicalMesial: true,
            coronaTopBuccal: true,
            coronaTopMedial: true,
            coronaTopLingual: true,
            coronaTopDistal: true,
            coronaTopOclusial: true,
        },
    },
    P28: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        locations: {},
        setOnLoad: {},
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
        },
    },
    P29: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        setOnLoad: {},
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
        locations: {
            rootCanal: true,
            periodontit: true,
            coronaLingualIncisalDistal: true,
            coronaLingualIncisalMiddle: true,
            coronaLingualIncisionMesial: true,
            coronaLingualMiddleDistal: true,
            coronaLingualMiddleMiddle: true,
            coronaLingualMiddleMesial: true,
            coronaLingualCervicalDistal: true,
            coronaLingualCervicalMiddle: true,
            coronaLingualCervicalMesial: true,
            coronaLabialIncisalDistal: true,
            coronaLabialIncisalMiddle: true,
            coronaLabialIncisionMesial: true,
            coronaLabialMiddleDistal: true,
            coronaLabialMiddleMiddle: true,
            coronaLabialMiddleMesial: true,
            coronaLabialCervicalDistal: true,
            coronaLabialCervicalMiddle: true,
            coronaLabialCervicalMesial: true,
            coronaTopBuccal: true,
            coronaTopMedial: true,
            coronaTopLingual: true,
            coronaTopDistal: true,
            coronaTopOclusial: true,
        },
        view: {
            coronaLingual: true,
            periodontit: true,
            rootCanal: true,
            coronaLingualIncisalDistal: true,
            coronaLingualIncisalMiddle: true,
            coronaLingualIncisionMesial: true,
            coronaLingualMiddleDistal: true,
            coronaLingualMiddleMiddle: true,
            coronaLingualMiddleMesial: true,
            coronaLingualCervicalDistal: true,
            coronaLingualCervicalMiddle: true,
            coronaLingualCervicalMesial: true,
            coronaLabial: true,
            coronaLabialIncisalDistal: true,
            coronaLabialIncisalMiddle: true,
            coronaLabialIncisionMesial: true,
            coronaLabialMiddleDistal: true,
            coronaLabialMiddleMiddle: true,
            coronaLabialMiddleMesial: true,
            coronaLabialCervicalDistal: true,
            coronaLabialCervicalMiddle: true,
            coronaLabialCervicalMesial: true,
            coronaTopBuccal: true,
            coronaTopMedial: true,
            coronaTopLingual: true,
            coronaTopDistal: true,
            coronaTopOclusial: true,
            root: true,
            gum: true,
        },
    },
    P30: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        setOnLoad: {},
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
        locations: {
            coronaLingualIncisalDistal: true,
            coronaLingualIncisalMiddle: true,
            coronaLingualIncisionMesial: true,
            coronaLingualMiddleDistal: true,
            coronaLingualMiddleMiddle: true,
            coronaLingualMiddleMesial: true,
            coronaLingualCervicalDistal: true,
            coronaLingualCervicalMiddle: true,
            coronaLingualCervicalMesial: true,
            coronaLabialIncisalDistal: true,
            coronaLabialIncisalMiddle: true,
            coronaLabialIncisionMesial: true,
            coronaLabialMiddleDistal: true,
            coronaLabialMiddleMiddle: true,
            coronaLabialMiddleMesial: true,
            coronaLabialCervicalDistal: true,
            coronaLabialCervicalMiddle: true,
            coronaLabialCervicalMesial: true,
            coronaTopBuccal: true,
            coronaTopMedial: true,
            coronaTopLingual: true,
            coronaTopDistal: true,
            coronaTopOclusial: true,
        },
        view: {
            coronaLingual: true,
            coronaLingualIncisalDistal: true,
            coronaLingualIncisalMiddle: true,
            coronaLingualIncisionMesial: true,
            coronaLingualMiddleDistal: true,
            coronaLingualMiddleMiddle: true,
            coronaLingualMiddleMesial: true,
            coronaLingualCervicalDistal: true,
            coronaLingualCervicalMiddle: true,
            coronaLingualCervicalMesial: true,
            coronaLabial: true,
            coronaLabialIncisalDistal: true,
            coronaLabialIncisalMiddle: true,
            coronaLabialIncisionMesial: true,
            coronaLabialMiddleDistal: true,
            coronaLabialMiddleMiddle: true,
            coronaLabialMiddleMesial: true,
            coronaLabialCervicalDistal: true,
            coronaLabialCervicalMiddle: true,
            coronaLabialCervicalMesial: true,
            coronaTopBuccal: true,
            coronaTopMedial: true,
            coronaTopLingual: true,
            coronaTopDistal: true,
            coronaTopOclusial: true,
            root: true,
            gum: true,
        },
    },
    P31: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        setOnLoad: {
            root: true,
        },
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
        locations: {
            root: true,
        },
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
        },
    },
    P32: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        setOnLoad: { rootCanal: true },
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
        locations: {
            rootCanal: true,
        },
        view: {
            root: true,
            rootCanal: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: true,
        },
    },
    P33: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        addLocation: (location, diagnose, originalDiagnose, toothId) => setOnlyOneLocationPlusFalse(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {},
        locations: {
            paradontit1: true,
            paradontit2: true,
            paradontit3: true,
            paradontit4: true,
            gum: false,
        },
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: false,
            paradontit1: true,
            paradontit2: true,
            paradontit3: true,
            paradontit4: true,
        },
    },
    P34: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        setOnLoad: {},
        locations: {
            paradontit1: true,
            paradontit2: true,
            paradontit3: true,
            paradontit4: true,
            gum: false,
        },
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: false,
            paradontit1: true,
            paradontit2: true,
            paradontit3: true,
            paradontit4: true,
        },
    },
    P35: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {
            gum: true,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
            root: false,
            rootCanal: false,
            periodontit: false,
        },
        locations: {
            gum: true,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
            root: false,
            rootCanal: false,
            periodontit: false,
        },
        view: {
            gum: true,
        },
    },
    P36: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {
            gum: true,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
            root: false,
            rootCanal: false,
            periodontit: false,
        },
        locations: {
            gum: true,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
            root: false,
            rootCanal: false,
            periodontit: false,
        },
        view: {
            root: false,
            coronaLingual: false,
            coronaLabial: false,
            coronaTop: false,
            gum: true,
        },
    },
    P37: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {
            gum: false,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
            root: false,
            rootCanal: false,
            periodontit: false,
            paradontit4: true,
        },
        locations: {
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
            root: false,
            rootCanal: false,
            periodontit: false,
            gum: false,
            paradontit4: true,
        },
        view: {
            root: true,
            coronaLingual: true,
            coronaLabial: true,
            coronaTop: true,
            gum: false,
            paradontit4: true,
        },
    },
    P38: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {
            root: undefined,
            gum: true,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
        },
        locations: {
            root: undefined,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
        },
        view: {
            root: true,
            coronaLingual: false,
            coronaLabial: false,
            coronaTop: false,
            gum: true,
        },
    },
    P39: {
        ageCategory: ['babyTeeth', 'adultTeeth'],
        functionType: 'toggleAll',
        addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
        setOnLoad: {
            root: true,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
        },
        locations: {
            root: true,
            coronaLingualIncisalDistal: false,
            coronaLingualIncisalMiddle: false,
            coronaLingualIncisionMesial: false,
            coronaLingualMiddleDistal: false,
            coronaLingualMiddleMiddle: false,
            coronaLingualMiddleMesial: false,
            coronaLingualCervicalDistal: false,
            coronaLingualCervicalMiddle: false,
            coronaLingualCervicalMesial: false,
            coronaLabialIncisalDistal: false,
            coronaLabialIncisalMiddle: false,
            coronaLabialIncisionMesial: false,
            coronaLabialMiddleDistal: false,
            coronaLabialMiddleMiddle: false,
            coronaLabialMiddleMesial: false,
            coronaLabialCervicalDistal: false,
            coronaLabialCervicalMiddle: false,
            coronaLabialCervicalMesial: false,
            coronaTopBuccal: false,
            coronaTopMedial: false,
            coronaTopLingual: false,
            coronaTopDistal: false,
            coronaTopOclusial: false,
            coronaLingual: false,
            coronaTop: false,
            coronaLabial: false,
            silant: false,
        },
        view: {
            root: true,
            gum: true,
        },
    },
};