export default [

    {
        id: 11,
        code: '11',
        title: 'Осмотр полости рта первичного больного',
        price: 200,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 12,
        code: '12',
        title: 'Справка о санации',
        price: 50,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 13,
        code: '13',
        title: 'Рентгенография с использованием аппарата &#171;визиограф&#187;',
        price: 350,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 131,
        code: '131',
        title: 'Повторная компьютерная радиовизиография',
        price: 150,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 132,
        code: '132,',
        title: 'Распечатка снимка',
        price: 50,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 14,
        code: '14',
        title: 'Консультация больного',
        price: 250,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 15,
        code: '15',
        title: 'Анестезия аппликационная',
        price: 100,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 16,
        code: '16',
        title: 'Анестезия инфильтрационная, внутриротовая проводниковая; инъекция',
        price: 350,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 161,
        code: '161',
        title: 'Дополнительная карпула анестетика',
        price: 150,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 17,
        code: '17',
        title: 'Избирательное пришлифовывание 1 зуба в постоянном прикусе',
        price: 150,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 18,
        code: '18',
        title: 'Трепанация, раскрытие полости зуба',
        price: 250,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 19,
        code: '19',
        title: 'Наложение и фиксация коффердама',
        price: 300,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 110,
        code: '110',
        title: 'Инкрустация зуба с использованием скайса',
        price: 1500,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 21,
        code: '21',
        title: 'Герметизация фиссуры неинвазивным методом с использованием Fissurit',
        price: 650,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 22,
        code: '22',
        title: 'Лечение среднего кариеса 1,5 класса по Блеку с использованием:',
        price: 234,
        unitType: 'pcs',
        available: true,
    }, {
        title: '      &#8212; стеклоиномера (СИЦ)',
        price: 1050,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 222,
        code: '222',
        title: '      &#8212; химиокомпозита (КМ хим)',
        price: 850,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 223,
        code: '223',
        title: '      &#8212; светокомпозита (КМ свет)',
        price: 1350,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 23,
        code: '23',
        title: 'Лечение среднего кариеса 2,3,4 класса по Блеку с использованием:',
        price: 123,
        unitType: 'pcs',
        available: true,
    }, {
        title: '       &#8212; стеклоиномера (СИЦ)',
        price: 1350,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 232,
        code: ' 232',
        title: ' химиокомпозита (КМ хим)',
        price: 1150,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 233,
        code: '233',
        title: ' светокомпозита (КМ свет)',
        price: 650,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 24,
        code: '24',
        title: 'Использование изолирующей подкладки для лечения глубокого кариеса, пульпита, периодонтита',
        price: 340,
        unitType: 'pcs',
        available: true,
    }, {
        title: 'Vitremer, Vitrebont',
        price: 450,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 242,
        code: '242',
        title: 'SDR',
        price: 234,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 243,
        code: '243',
        title: 'Biodenit',
        price: 234,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 26,
        code: '26',
        title: 'Коррекция формы и цвета зуба с помощью композитного винира (прямой метод)',
        price: 3000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 27,
        code: '27',
        title: 'Фиксация анкерного штифта c использованием материала:',
        price: 234,
        unitType: 'pcs',
        available: true,
    }, {
        id: 271,
        code: '271',
        title: 'Фиксация анкерного штифта c использованием материала: Fudji, Vitremer',
        price: 150,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 272,
        code: '272,',
        title: 'Фиксация анкерного штифта c использованием материала: Corecem',
        price: 234,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 28,
        code: '28',
        title: 'Изготовление анкерного штифта:',
        price: 234,
        unitType: 'pcs',
        available: true,
    }, {
        title: '      &#8212; системы Unimetric (титановый)',
        price: 150,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 282,
        code: '282',
        title: '      &#8212; системы Glassix (стекловолоконные)',
        price: 350,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 283,
        code: '283',
        title: 'Дополнительный анкерный штифт титановый/стекловолоконный',
        price: 300 / 500,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 29,
        code: '29',
        title: 'Подготовка корневого канала подштифт, штифтовкладку',
        price: 350,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 210,
        code: '210',
        title: 'Адгезивная мостовидная конструкция (3 ед)',
        price: 8250,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 211,
        code: '211',
        title: 'Наложение девитализирующей пасты',
        price: 225,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 212,
        code: '212',
        title: 'Временная пломба, повязка /свет временная пломба',
        price: 100 / 150,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 213,
        code: '213',
        title: 'Лечение пульпита и периодонтита с пломбированием каналов гуттаперчей:',
        price: 234,
        unitType: 'pcs',
        available: true,
    }, {
        title: '     &#8212; однокоренной зуб',
        price: 1350,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 2132,
        code: '2132',
        title: '8212; двухкорневой зуб',
        price: 2025,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 2133,
        code: '2133',
        title: '8212; трехкорневой зуб',
        price: 2700,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 214,
        code: '214',
        title: 'Эндодонтическая калибровка одного канала',
        price: 250,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 215,
        code: '21,5',
        title: 'Эндодонтическая калибровка одного канала одного канала',
        price: 234,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 216,
        code: '216',
        title: 'Временное пломбирование 1 канала',
        price: 250,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 217,
        code: '217',
        title: 'Восстановление зуба при лечении пульпита и периодонтита пломбой из светокомпозита (КМ свет):',
        price: 234,
        unitType: 'pcs',
        available: true,
    }, {
        id: 2171,
        code: '2171',
        title: '&#8212; однокорневой зуб',
        price: 2600,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 2172,
        code: '2172',
        title: '     &#8212; многокорневой зуб',
        price: 2800,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 218,
        code: '218',
        title: 'Распломбирование одного канала:',
        price: 234,
        unitType: 'pcs',
        available: true,
    }, {
        title: '8212; пломбированного пастой',
        price: 450,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 2182,
        code: '2182,',
        title: '8212; пломбированного цементом',
        price: 550,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 219,
        code: '219',
        title: 'Извлечение инородного тела из канала, удаление в/к штифта',
        price: 600,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 220,
        code: '220',
        title: 'Эндодонтическое отбеливание 1 зуба',
        price: 450,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 31,
        code: '31',
        title: 'Удаление зубных отложений с использованием ультрозвукового скалера, в тч:',
        price: 234,
        unitType: 'pcs',
        available: true,
    }, {
        title: '     &#8212; снятия налета с 1 зуба',
        price: 110,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 312,
        code: '312',
        title: '     &#8212; снятие зубного камня с 1 зуба',
        price: 185,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 32,
        code: '32',
        title: ' Полировка 1 зуба после снятия зубных отложений',
        price: 45,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 33,
        code: '33',
        title: ' снятия зубных отложений с помощью   системы Air-Flow',
        price: 150,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 34,
        code: '34',
        title: ' Vector-терапия в области 1 зуба',
        price: 190,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 35,
        code: '35',
        title: 'Медикаментозная обработка зубо-десневых карманов',
        price: 500,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 36,
        code: '36',
        title: 'Шинирование 1 зуба светокомпозитом',
        price: 1900,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 37,
        code: '37',
        title: 'Медикаментозная обработка слизистой оболочки полости рта',
        price: 250,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 38,
        code: '38',
        title: 'Диатермокоагуляция слизистой',
        price: 250,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 39,
        code: '39',
        title: 'Покрытие  реминерализирующим средством  1-2 постоянных зубов',
        price: 190,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 310,
        code: '310',
        title: 'Покрытие реминерализирующим средством более 2х постоянных зубов',
        price: 420,
        unitType: 'pcs',
        available: true,
    },

    {
        id: 414,
        code: 414,
        title: 'дополнительная ед литья',
        price: 500,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 415,
        code: 415,
        title: 'каркас из диоксида циркония',
        price: 8000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 416,
        code: 416,
        title: 'напыление 1 ед',
        price: 200,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 417,
        code: 417,
        title: 'временная конструкция (протемп) 1ед',
        price: 500,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 52,
        code: 52,
        title: 'приварка кламмера, зуба',
        price: 1500,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 61,
        code: 61,
        title: '1-5 ед',
        price: 3500,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 62,
        code: 62,
        title: '6-10 ед',
        price: 500,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 63,
        code: 63,
        title: '10-13 ед',
        price: 5800,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 71,
        code: 71,
        title: 'металлический литой',
        price: 500,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 72,
        code: 72,
        title: ' металлический гнутый',
        price: 300,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 73,
        code: 73,
        title: ' дентоальвеолярный',
        price: 350,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 74,
        code: 74,
        title: 'армирование верхней челюсти',
        price: 900,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 75,
        code: 75,
        title: 'армирование нижней челюсти',
        price: 900,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 76,
        code: 76,
        title: 'индивидуальная ложка',
        price: 1600,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 82,
        code: 82,
        title: 'импортный гарнитур для бюгельной конструкции',
        price: 200,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 83,
        code: 83,
        title: 'моделирование бюгельного протеза',
        price: 2500,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 84,
        code: 84,
        title: 'дублирование модели',
        price: 3000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 85,
        code: 85,
        title: 'литьё каркаса на огнеупорной модели',
        price: 3500,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 86,
        code: 86,
        title: 'дуга на верхнюю челюсть',
        price: 2000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 87,
        code: 87,
        title: 'дуга на нижнюю челюсть',
        price: 2000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 88,
        code: 88,
        title: 'седло(сетка)для крепления с пластмассой',
        price: 700,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 89,
        code: 89,
        title: 'многозвеньевая шина для крепления базиса',
        price: 550,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 810,
        code: 810,
        title: 'базис',
        price: 1000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 811,
        code: 811,
        title: 'ограничитель базиса',
        price: 700,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 812,
        code: 812,
        title: 'формирование искуственной десны',
        price: 900,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 813,
        code: 813,
        title: 'фрезеровка под интерлог',
        price: 800,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 814,
        code: 814,
        title: 'нейлоновый протез',
        price: 5000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 815,
        code: 815,
        title: 'частичный нейлоновый протез',
        price: 5000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 816,
        code: 816,
        title: 'протез частичный съемный acri Free 1-4 ед',
        price: 2000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 92,
        code: 92,
        title: 'коронка, зуб металлокерамическая',
        price: 4000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 93,
        code: 93,
        title: 'корнка  м/к на золоте',
        price: 8000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 94,
        code: 94,
        title: 'винир керамический',
        price: 2000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 95,
        code: 95,
        title: 'безметалловая керамика',
        price: 2000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 96,
        code: 96,
        title: 'облицовка диоксида циркония',
        price: 7000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 97,
        code: 97,
        title: 'вкладка из пресскерамики',
        price: 7000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 98,
        code: 98,
        title: 'металлопластмассовая коронка',
        price: 2000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 99,
        code: 99,
        title: 'металлопластмассовый зуб',
        price: 2000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 912,
        code: 912,
        title: 'накладка окклюзионная',
        price: 500,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 913,
        code: 913,
        title: 'кламмер опорно-удерживающий',
        price: 900,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 914,
        code: 914,
        title: 'лазерная пайка 1 ед',
        price: 850,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 101,
        code: 101,
        title: 'установка замка 1шт',
        price: 3000,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 103,
        code: 103,
        title: 'замена матрицы в замке бюгеля 1 ед',
        price: 700,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 104,
        code: 104,
        title: 'напыление  Niti',
        price: 700,
    },
    {
        id: 111,
        code: 111,
        title: 'УФИ гель П частичный',
        price: 600,
        unitType: 'pcs',
        available: true,
    },
    {
        id: 112,
        code: 112,
        title: 'УФИ гель П полный',
        price: 1200,
        unitType: 'pcs',
        available: true,
    },

];
