# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node

pipelines:
  branches:
    master:
      - step:
          name: Deploy to production
          deployment: production
          script:
            - npm install
            - npm run build
            - ssh -T webuser@165.227.180.111 rm -fr $REMOTE_PATH*
            - pipe: atlassian/sftp-deploy:0.5.0
              variables:
                USER: 'webuser'
                SERVER: '165.227.180.111'
                REMOTE_PATH: $REMOTE_PATH
                LOCAL_PATH: 'dist/*'
                DEBUG: 'true'
