export default {
  patient: {
    ID: null,
    organizationID: null,
    firstName: null,
    lastName: null,
    avatar: null,
    phone: null,
    email: null,
    birthday: null,
    source: null,
    address: null,
    allergy: [],
    notes: [],
    plans: [
      {
        title: 'Plan № 1',
        id: 0.7100688909468207,
        showInJaw: true,
        procedures: [],
        date: '[native Date Mon Apr 15 2019 11:41:21 GMT+0500 (Узбекистан, стандартное время)]',
        author: {
          ID: 2,
          avatar: 'https://dental-api.owl.team/s3/files/user/2/avatar/5fb90badb37c5821b6d95526a41a9504.jpeg',
          firstName: 'TImur23',
          lastName: 'Sarvarov',
          },
        },
    ],
    diagnosis: [],
    // procedures: [],
    procedurePlans: [],
    anamnes: [],
    created: null,
    updated: null,
    rating: null,
    color: null,
    files: [],
  },
};
