export default {
    patient: {
        ID: null,
        organizationID: null,
        firstName: null,
        lastName: null,
        avatar: null,
        phone: null,
        email: null,
        birthday: null,
        source: null,
        address: null,
        allergy: [],
        notes: [],
        plans: [],
        diagnosis: [],
        invoices: [],
        anamnesis: [],
        created: null,
        updated: null,
        rating: null,
        color: null,
        files: [],
    },
};
