export default {
    status: null,
    ID: null,
    organizationID: null,
    firstName: null,
    lastName: null,
    avatar: null,
    phone: null,
    email: null,
    birthday: null,
    source: null,
    address: null,
    allergy: [],
    notes: [],
    plans: [],
    currentPlan: null,
    procedures: {},
    diagnosis: [],
    invoices: [],
    anamnesis: [],
    created: null,
    updated: null,
    rating: null,
    color: null,
    files: [],
    ageCategory: null,
};