/* eslint-disable no-tabs */


export default [{
        code: 'K00',
        title: 'Нарушения развития и прорезывания зубов',
        codes: [{
                code: 'K00.0',
                title: 'Адентия',
                explain: 'Congenitally missing teeth - complete or partial',
                templateCode: 'P21',
                available: true,
            },
            {
                code: 'K00.1',
                title: 'Сверхкомплектные зубы',
                explain: 'Mesiodens',
                templateCode: 'P22',
                available: true,
            },
            {
                code: 'K00.2',
                title: 'Отклонения от размера и формы зуба',
                explain: 'Macr/micro-dontia, dens in dente, cocrescence, fusion, gemination, peg',
                templateCode: 'P23',
                available: true,
            },
            {
                code: 'K00.3',
                title: 'Крапчатые  зубы',
                explain: 'Fluorosis',
                templateCode: 'P24',
                available: true,
            },
            {
                code: 'K00.4',
                title: 'Нарушение формирования зубов',
                explain: 'Enamel hypoplasia, dilaceration, Turner',
                templateCode: 'P23',
                available: true,
            },
            {
                code: 'K00.5',
                title: 'Наследственные нарушения структуры зуба',
                explain: 'Amylo/dentino-genisis imperfecta',
                templateCode: 'P25',
                available: true,
            },
            {
                code: 'K00.6',
                title: 'Нарушения прорезывания зубов',
                explain: 'Natal/neonatal teeth, retained deciduous tooth, premature, late',
                templateCode: 'P26',
                available: true,
            },
            {
                code: 'K00.7',
                title: 'Синдром прорезывания зубов',
                templateCode: 'P26',
                available: true,
            },
            {
                code: 'K00.8',
                title: 'Другие нарушения развития зубов',
                explain: 'Colour changes due to blood incompatability, biliary, porphyria, tetyracy',
                templateCode: 'P27',
                available: true,
            },
            {
                code: 'K00.9',
                title: 'Нарушение развития зубов неуточненные',
                templateCode: 'P27',
                available: true,
            },
        ],
    },

    {
        code: 'K01',
        title: 'Ретенированные и импактные зубы',
        codes: [{
                code: 'K01.0',
                title: 'Ретенированные зубы',
                explain: 'Distinguish from impacted tooth',
                templateCode: 'P28',
                available: true,
            },
            {
                code: 'K01.1',
                title: 'Импактные зубы',
                explain: 'In contact with another tooth',
                templateCode: 'P28',
                available: true,
            },
        ],
    },
    {
        code: 'K02',
        title: 'Кариес зубов',
        codes: [{
                code: 'K02.0',
                title: 'Кариес эмали стадия белого (мелового) пятна',
                explain: 'Restoration, amalgam, composite, resin',
                templateCode: 'P29',
                available: true,
            },
            {
                code: 'K02.1',
                title: 'Кариес дентина',
                explain: 'Restoration, amalgam, composite, resin',
                templateCode: 'P29',
                available: true,
            },
            {
                code: 'K02.2',
                title: 'Кариес цемента',
                explain: 'Restoration, amalgam, composite, resin, crown',
                templateCode: 'P29',
                available: true,
            },
            {
                code: 'K02.3',
                title: 'Приостановившийся кариес зубов',
                explain: 'Restoration, amalgam, composite, resin, crown',
                templateCode: 'P29',
                available: true,
            },
            {
                code: 'K02.4',
                title: 'Одонтоклазия детская меланодентия, меланодонтоклазия',
                explain: 'Infantile meladontia',
                templateCode: 'P29',
                available: true,
            },
            {
                code: 'K02.8',
                title: 'Другой уточненный кариес зубов',
                templateCode: 'P29',
                available: true,
            },
            {
                code: 'K02.9',
                title: 'Кариес зубов неуточненный',
                templateCode: 'P29',
                available: true,
            },
        ],
    },
    {
        code: 'K03',
        title: 'Другие болезни твердых тканей зубов',
        codes: [{
                code: 'K03.0',
                title: 'Повышенное стирание зубов',
                templateCode: 'P30',
                available: true,
            },
            {
                code: 'K03.1',
                title: 'Сошлифовывание (абразивный знос) зубов',
                templateCode: 'P30',
                available: true,
            },
            {
                code: 'K03.2',
                title: 'Эрозия зубов',
                explain: 'Vomiting, anorexia, bulhemia, acid, diet',
                templateCode: 'P30',
                available: true,
            },
            {
                code: 'K03.3',
                title: 'Патологическая резорбция зубов',
                explain: 'Pink spot',
                templateCode: 'P31',
                available: true,
            },
            {
                code: 'K03.4',
                title: 'Гиперцементоз',
                templateCode: 'P31',
                available: true,
            },
            {
                code: 'K03.5',
                title: 'Анкилоз зубов',
                explain: 'Pink spot',
                templateCode: 'P31',
                available: true,
            },
            {
                code: 'K03.6',
                title: 'Отложения (наросты) на зубах',
                explain: 'Pigmentation, tobacco, betel, plaque, calculus, scaling and polishing',
                templateCode: 'P30',
                available: true,
            },
            {
                code: 'K03.7',
                title: 'Изменения цвета твердых тканей зубов после прорезывания',
                explain: 'Metal, pulpal bleeding, betel, tobacco',
                templateCode: 'P30',
                available: true,
            },
            {
                code: 'K03.8',
                title: 'Другие  уточненные болезни твердых тканей зубов',
                explain: 'Sensitive dentine',
                templateCode: 'P30',
                available: true,
            },
            {
                code: 'K03.9',
                title: 'Болезнь твердых тканей зубов неуточненная',
                explain: '',
                templateCode: 'P30',
                available: true,
            },
        ],
    },
    {
        code: 'K04',
        title: 'Болезни пульпы и периапикальных тканей',
        codes: [{
                code: 'K04.0',
                title: 'Пульпит',
                explain: 'Pulp cap, root canal treatment,sedative dressing, endodontic,obturate',
                templateCode: 'P32',
                available: true,
            },
            {
                code: 'K04.1',
                title: 'Некроз пульпы (гангрена пульпы)',
                explain: 'Gangrene, root canal treatment,sedative dressing, endodontic,obturate',
                templateCode: 'P32',
                available: true,
            },
            {
                code: 'K04.2',
                title: 'Дегенерация пульпы дентикли, пульпарные камни',
                explain: 'Pulp stones, sclerosis',
                templateCode: 'P32',
                available: true,
            },
            {
                code: 'K04.3',
                title: 'Неправильное формирование твердых тканей в пульпе',
                explain: '2ndary dentine - excludes pulp stones(K04.2)',
                templateCode: 'P32',
                available: true,
            },
            {
                code: 'K04.4',
                title: 'Острый апикальный периодонтит пульпарного происхождения ',
                explain: 'Root canal treatment,endodontic,obturate, abcess',
                templateCode: 'P07',
                available: true,
            },
            {
                code: 'K04.5',
                title: 'Хронический апикальный периодонтит (апикальная гранулема)',
                explain: 'Granuloma, root canal treatment,endodontic,obturate,abcess',
                templateCode: 'P07',
                available: true,
            },
            {
                code: 'K04.6',
                title: 'Периапикальный абсцесс со свищем  ',
                explain: 'Root canal treatment,endodontic,obturate,abcess',

                templateCode: 'P07',
                available: true,
            },
            {
                code: 'K04.7',
                title: 'Периапикальный абсцесс без свища',
                explain: 'Root canal treatment,endodontic,obturate,abcess',
                templateCode: 'P07',
                available: true,
            },
            {
                code: 'K04.8',
                title: 'Корневая киста ',
                explain: 'Apical cyst, enucleate,apicectomy, apicoectomy',
                templateCode: 'P07',
                available: true,
            },
            {
                code: 'K04.9',
                title: 'Другие неуточненные болезни пульпы и периапикальных тканей',
                templateCode: 'P07',
                available: true,
            },
        ],
    },
    {
        code: 'K05',
        title: 'Гингивит и болезни пародонта',
        codes: [{
                code: 'K05.0',
                title: 'Острый гингивит',
                explain: 'Gingivitis, bleeding gums, scaling',
                templateCode: 'P33',
                available: true,
            },
            {
                code: 'K05.1',
                title: 'Хронический гингивит',
                explain: 'Gingivitis, bleeding gums, scaling, ulcerative - excludes Vincent',
                templateCode: 'P33',
                available: true,
            },
            {
                code: 'K05.2',
                title: 'Острый парадонтит',
                explain: 'Gingivitis, bleeding gums, scaling ',
                templateCode: 'P33',
                available: true,
            },
            {
                code: 'K05.3',
                title: 'Хронический пародонтит',
                explain: 'Gingivitis, chronic pericoronitis, bleeding gums, scaling',
                templateCode: 'P33',
                available: true,
            },
            {
                code: 'K05.4',
                title: 'Пародонтоз',
                explain: 'Juvenile,gingivitis, bleeding gums, scaling, curettage',
                templateCode: 'P33',
                available: true,
            },
            {
                code: 'K05.5',
                title: 'Другие болезни пародонта',
                explain: 'Gingivitis, bleeding gums, scaling',
                templateCode: 'P33',
                available: true,
            },
            {
                code: 'K05.6',
                title: 'Другие болезни пародонта, неуточненные',
                templateCode: 'P33',
                available: true,
            },
        ],
    },
    {
        code: 'K06',
        title: 'Другие изменения десны и беззубого альвеолярного края',
        codes: [{
                code: 'K06.0',
                title: 'Рецессия десны',
                explain: 'Gingiva, recession',
                templateCode: 'P33',
                available: true,
            },
            {
                code: 'K06.1',
                title: 'Гипертрофия десны',
                explain: 'Fibromatosis',
                templateCode: 'P20',
                available: true,
            },
            {
                code: 'K06.2',
                title: 'Поражения десны и беззубого альвеолярного края, обусловленные травмой',
                explain: 'Denture hyperplasia occlusion, toothbrushing',
                templateCode: 'P35',
                available: true,
            },
            {
                code: 'K06.8',
                title: 'Другие уточненные изменения десны и беззубого альвеолярного края',
                explain: 'Gingival cyst, epulis, pyogenic granuloma',
                templateCode: 'P35',
                available: true,
            },
            {
                code: 'K06.9',
                title: 'Изменения десны и беззубого альвеолярного края неуточненные',
                templateCode: 'P35',
                available: true,
            },
        ],
    },
    {
        code: 'K07',
        title: 'Челюстно-лицевые аномалии (включая аномалии прикуса)',
        codes: [{
                code: 'K07.0',
                title: 'Основные аномалии размеров челюстей',
                explain: 'Gingiva, recession',
                templateCode: 'P04',
                available: true,
            },
            {
                code: 'K07.1',
                title: 'Аномалии челюстно-черепных соотношений',
                explain: 'Asymetry, pro/retrognathic, Cl 2, Cl 3, osteotomy, orthognathic, ortho',
                templateCode: 'P04',
                available: true,
            },
            {
                code: 'K07.2',
                title: 'Аномалии соотношения зубных дуг',
                explain: 'Overjet, overbite, crossbite,midline deviation, orthodontic, banding',
                templateCode: 'P04',
                available: true,
            },
            {
                code: 'K07.3',
                title: 'Аномалии положения зубов',
                explain: 'Crowding, rotation, distema, transposition',
                templateCode: 'P04',
                available: true,
            },
            {
                code: 'K07.4',
                title: 'Аномалии прикуса неуточненные',
                templateCode: 'P04',
                available: true,
            },
            {
                code: 'K07.5',
                title: 'Челюстно-лицевые аномалии функционального происхождения',
                explain: 'Mouth breathing, abnormal swallowing, habits',
                templateCode: 'P04',
                available: true,
            },
            {
                code: 'K07.6',
                title: 'Болезни ВЧНС',
                explain: 'Dislocation, TMJ, click, pain',
                templateCode: 'P04',
                available: true,
            },
            {
                code: 'K07.8',
                title: 'Другие денто-лицевые аномалии',
                explain: 'Dislocation, TMJ, click, pain',
                templateCode: 'P04',
                available: true,
            },
            {
                code: 'K07.9',
                title: 'Денто-лицевая аномалия, неуточненная',
                templateCode: 'P04',
                available: true,
            },
        ],
    },
    {
        code: 'K08',
        title: 'Другие изменения зубов и их опорного аппарата',
        codes: [{
                code: 'K08.0',
                title: 'Эксфолиация зубов из-за системных нарушений',
                explain: 'Hypophosphatasia, scurvy',
                templateCode: 'P04',
                available: true,
            },
            {
                code: 'K08.1',
                title: 'Потеря зубов вследствие несчастного случая, удаления или локализованного пародонтита',
                explain: 'Denture, bridge, implant, space maintainer',
                templateCode: 'P18',
                available: true,
            },
            {
                code: 'K08.2',
                title: 'Атрофия беззубого альвеолярного края',
                explain: 'Gingival mucosal graft',
                templateCode: 'P37',
                available: true,
            },
            {
                code: 'K08.3',
                title: 'Оставшийся корень зуба',
                explain: 'Root rest',
                templateCode: 'P38',
                available: true,
            },
            {
                code: 'K08.8',
                title: 'Другие уточненные изменения зубов и их опорного аппарата',
                explain: 'Toothache NOS',
                templateCode: 'P29',
                available: true,
            },
            {
                code: 'K08.9',
                title: 'Изменения зубов и их опорного аппарата неуточненное',
                templateCode: 'P29',
                available: true,
            },
        ],
    },
    {
        code: 'K09',
        title: 'Кисты области рта, не классифицированные в других  рубриках',
        codes: [{
                code: 'K09.0',
                title: 'Киста при прорезывании зубов',
                explain: 'cyst, eruption, gingival, Kerato, dentigerous,lateral periodontal',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K09.1',
                title: 'Ростовые (неодонтогенные) кисты области рта',
                explain: 'Nasopalatine cyst',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K09.2',
                title: 'Другие кисты челюстей',
                explain: 'Nasopalatine cyst',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K09.8',
                title: 'Кисты полости рта, не классифицированные в других рубриках',
                explain: 'Dermoid cyst',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K09.9',
                title: 'Кисты полости рта, неуточненные',
                templateCode: 'P01',
                available: true,
            },
        ],
    },
    {
        code: 'K10',
        title: 'Другие болезни челюстей',
        codes: [{
                code: 'K10.0',
                title: 'Нарушения развития челюстей',
                explain: 'Tori',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K10.1',
                title: 'Гигантоклеточная гранулема центральная',
                explain: '',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K10.2',
                title: 'Воспалительные заболевания челюстей',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K10.3',
                title: 'Альвеолит челюстей альвеолярный остеит, сухая лунка',
                explain: 'Osteomyelitis, sequestra',
                templateCode: 'P39',
                available: true,
            },
            {
                code: 'K10.8',
                title: 'Другие уточненные болезни челюстей',
                explain: 'Dry socket',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K10.9',
                title: 'Болезнь челюстей неуточненная',
                templateCode: 'P01',
                available: true,
            },
        ],
    },
    {
        code: 'K11',
        title: 'Болезни слюнных желез',
        codes: [{
                code: 'K11.0',
                title: 'Атрофия слюнной железы',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K11.1',
                title: 'Гипертрофия слюнной железы',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K11.2',
                title: 'Сиалоадеит',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K11.3',
                title: 'Абсцесс слюнной железы',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K11.4',
                title: 'Свищ слюнной железы',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K11.5',
                title: 'Сиалолитиаз, камни в слюнном протоке',
                explain: 'Salivary calculus, stone',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K11.6',
                title: 'Мукоцеле слюнной железы, ранула',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K11.7',
                title: 'Нарушение секреции слюнных желез',
                explain: 'Xerostoma, dry mouth',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K11.8',
                title: 'Другие болезни слюнных желез',
                explain: 'Miculicz',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K11.9',
                title: 'Заболевание слюнной железы неуточненное',
                templateCode: 'P01',
                available: true,
            },
        ],
    },
    {
        code: 'K12',
        title: 'Стоматит и родственные поражения',
        codes: [{
                code: 'K12.0',
                title: 'Рецидивирующие афты полости рта',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K12.1',
                title: 'Другие формы стоматита',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K12.2',
                title: 'Флегмона и абсцесс области рта',
                templateCode: 'P01',
                available: true,
            },
        ],
    },
    {
        code: 'K13',
        title: 'Другие болезни губ и слизистой оболочки полости рта',
        codes: [{
                code: 'K13.0',
                title: 'Болезни губ',
                explain: 'Angular chelitis',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K13.1',
                title: 'Прикусывание щеки и губ',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K13.2',
                title: 'Лейкоплакия и другие изменения  эпителия  полости рта, включая язык',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K13.3',
                title: 'Волосатая лейкоплакия',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K13.4',
                title: 'Гранулема и гранулемоподобные поражения слизистой оболочки полости рта',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K13.5',
                title: 'Подслизистый фиброз полости рта',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K13.6',
                title: 'Гиперплазия СОПР вследствие раздражения',
                templateCode: 'P01',
                available: true,
            },
            {
                code: 'K13.7',
                title: 'Другие и неуточненные поражения слизистой оболочки полости рта',
                templateCode: 'P16',
                available: true,
            },
        ],
    },
    {
        code: 'K14',
        title: 'Болезни языка',
        codes: [{
                code: 'K14.0',
                title: 'Глоссит',
                explain: 'Ulcer, abscess',
                templateCode: 'P16',
                available: true,
            },
            {
                code: 'K14.1',
                title: 'Географический язык, эксфолиативный глоссит',
                templateCode: 'P16',
                available: true,
            },
            {
                code: 'K14.2',
                title: 'Срединный ромбовидный глоссит',
                templateCode: 'P16',
                available: true,
            },
            {
                code: 'K14.3',
                title: 'Гипертрофия сосочков языка',
                explain: 'Black hairy tongue',
                templateCode: 'P16',
                available: true,
            },
            {
                code: 'K14.4',
                title: 'Атрофия сосочков языка',
                templateCode: 'P16',
                available: true,
            },
            {
                code: 'K14.5',
                title: 'Складчатый, морщинистый, бороздчатый, расщепленный язык',
                explain: 'Scrotal, fissured tongue',
                templateCode: 'P16',
                available: true,
            },
            {
                code: 'K14.6',
                title: 'Глоссодиния',
                templateCode: 'P16',
                available: true,
            },
            {
                code: 'K14.8',
                title: 'Глоссодиния неуточненная',
                templateCode: 'P16',
                available: true,
            },
            {
                code: 'K14.9',
                title: 'Болезнь языка неуточненная',
                templateCode: 'P16',
                available: true,
            },
        ],
    },
];