/* eslint-disable no-tabs */

export default [{
    code: '1',
    title: 'Diagnose',
    codes: [{
        code: '1.1',
        title: 'Consultation and treatment plan',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P01',
        state: '',
    },
    {
        code: '1.2',
        title: 'Periapical X-Ray',
        description: '',
        defaultManipulations: [1, 2],
        available: true,
        templateCode: 'P01',
        state: '',
    },
    {
        code: '1.3',
        title: 'Bitewing X-Ray',
        description: '',
        price: 12,
        available: false,
        templateCode: 'P01',
        state: '',
    },
    {
        code: '1.4',
        title: 'Panoramic X-Ray',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P01',
        state: '',
    },
    {
        code: '1.5',
        title: 'Cephalometric X-ray',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P01',
        state: '',
    },
    {
        code: '1.6',
        title: 'ConeBeam CT X-ray (1 jaw)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P01',
        state: '',
    },
    {
        code: '1.7',
        title: 'ConeBeam CT X-ray (2 jaw)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P01',
        state: '',
    },
    {
        code: '1.8',
        title: 'Blood test',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P01',
        state: '',
    },
    ],
},
{
    code: '2',
    title: 'Restoration',
    codes: [{
        code: '2.1',
        title: 'Composite filling (minimal)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P02',
        state: '',
    },
    {
        code: '2.2',
        title: 'Composite filling (moderate)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P02',
        state: '',
    },
    {
        code: '2.3',
        title: 'Composite filling (enlarged)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P02',
        state: '',
    },
    {
        code: '2.4',
        title: 'Composite filling (extensive)',
        description: '',
        price: 12,
        templateCode: 'P02',
        state: '',
    },
    {
        code: '2.5',
        title: 'Cosmetic Composite resin restoration',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P02',
        state: '',
    },
    {
        code: '2.6',
        title: 'Tooth gap filling',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P02',
        state: '',
    },
    {
        code: '2.7',
        title: 'Sealant',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P03',
        state: '',

    },
    {
        code: '2.8',
        title: 'Composite veneer',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P06',
        state: '',
    },
    {
        code: '2.9',
        title: 'Dental dam',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P04',
        state: '',
    },
    ],
},
{
    code: '3',
    title: 'Root Canal',
    codes: [{
        code: '3.1',
        title: 'Root canal treatment (anterior)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P07',
        state: '',
    },
    {
        code: '3.2',
        title: 'Root canal treatment (premolar)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P07',
        state: '',
    },
    {
        code: '3.3',
        title: 'Root canal treatment (molar)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P07',
        state: '',
    },
    {
        code: '3.4',
        title: 'Root canal re-treatment (anterior)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P07',
        state: '',
    },
    {
        code: '3.5',
        title: 'Root canal re-treatment (premolar)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P07',
        state: '',
    },
    {
        code: '3.6',
        title: 'Root canal re-treatment (molar)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P07',
        state: '',
    },
    {
        code: '3.7',
        title: 'Direct pulp capping',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P07',
        state: '',
    },
    {
        code: '3.8',
        title: 'Abscess drainage/Abscess treatment',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P07',
        state: '',
    },
    ],
},
{
    code: '4',
    title: 'Hygiena',
    codes: [{
        code: '4.1',
        title: 'Cleaning and polishing (Mild calculus)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P04',
        state: '',
    },
    {
        code: '4.2',
        title: 'Cleaning and polishing (Moderate calculus)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P04',
        state: '',
    },
    {
        code: '4.3',
        title: 'Cleaning and polishing (Heavy calculus)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P04',
        state: '',
    },
    {
        code: '4.4',
        title: 'Teeth cleaning and polishing under local anesthetics',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P04',
        state: '',
    },
    {
        code: '4.5',
        title: 'Periodontal pocket treatment (non-surgical)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P05',
        state: '',
    },
    {
        code: '4.6',
        title: 'Operculectomy',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P20',
        state: '',
    },
    {
        code: '4.7',
        title: 'Gum contouring surgery',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P20',
        state: '',
    },
    {
        code: '4.8',
        title: 'Gum grafting',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P20',
        state: '',
    },
    ],
},
{
    code: '5',
    title: 'Whitening',
    codes: [{
        code: '5.1',
        title: 'At-home whitening kit (Zoom)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P04',
        state: '',
    },
    {
        code: '5.2',
        title: 'In-office laser whitening with Zoom 2',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P04',
        state: '',
    },
    {
        code: '5.3',
        title: 'Whitening Combination Package',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P04',
        state: '',
    },
    {
        code: '5.4',
        title: 'Internal bleaching',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P04',
        state: '',
    },
    ],
},
{
    code: '6',
    title: 'Prosthetics',
    codes: [{
        code: '6.1',
        title: 'Crown removal',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P09',
        state: '',
    },
    {
        code: '6.2',
        title: 'Temporary crown (PMMA)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P10',
        state: '',
    },
    {
        code: '6.3',
        title: 'Re-cement crown',
        description: '',
        price: 12,
        templateCode: 'P10',
        state: '',
    },
    {
        code: '6.4',
        title: 'Composite inlay',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P11',
        state: '',
    },
    {
        code: '6.5',
        title: 'All-porcelain inlay (Emax CAD)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P11',
        state: '',
    },
    {
        code: '6.6',
        title: 'Composite onlay',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P11',
        state: '',
    },
    {
        code: '6.7',
        title: 'All-porcelain onlay (Emax CAD)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P11',
        state: '',
    },
    {
        code: '6.8',
        title: 'All-porcelain overlay (Emax CAD)',
        descriptionn: '',
        price: 12,
        available: true,
        templateCode: 'P11',
        state: '',
    },
    {
        code: '6.9',
        title: 'Porcleain fused to titanium crown (CAD/CAM)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P12',
        state: '',
    },
    ],
},
{
    code: '7',
    title: 'Implantation',
    codes: [

        {
            code: '7.1',
            title: 'Nobel Biocare/SGS Switzerland dental implant',
            description: '',
            price: 12,
            available: true,
            templateCode: 'P13',
            ageCategory: [0],
            state: '',
        },
        {
            code: '7.2',
            title: 'Bone grafting',
            description: '',
            price: 12,
            available: true,
            templateCode: 'P14',
            ageCategory: [0],
            state: '',
        },
        {
            code: '7.3',
            title: 'Guided bone regeneration membrane',
            description: '',
            price: 12,
            templateCode: 'P14',
            ageCategory: [0],
            state: '',
        },
        {
            code: '7.4',
            title: 'Sinus augmentation (Closed)',
            description: '',
            price: 12,
            available: true,
            templateCode: 'P14',
            ageCategory: [0],
            state: '',
        },
        {
            code: '7.5',
            title: 'Sinus augmentation (Open)',
            description: '',
            price: 12,
            available: true,
            templateCode: 'P15',
            ageCategory: [0],
            state: '',
        },
        {
            code: '7.6',
            title: 'All on 8 (Nobel Biocare/SGS Switzerland dental implant)',
            description: '',
            price: 12,
            available: true,
            templateCode: 'P16',
            ageCategory: [0],
            state: '',
        },
        {
            code: '7.7',
            title: 'All on 6 (Nobel Biocare/SGS Switzerland dental implant)',
            description: '',
            price: 12,
            available: true,
            templateCode: 'P16',
            ageCategory: [0],
            state: '',
        },
    ],
},
{
    code: '8',
    title: 'Orthondontic',
    codes: [{
        code: '8.1',
        title: 'Traditional metal braces - Simple case: no extraction required',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P17',
        state: '',

    },
    {
        code: '8.2',
        title: 'Traditional metal braces - Requires extraction (fee for extraction is not included)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P17',
        state: '',
    },
    {
        code: '8.3',
        title: 'Traditional metal braces - Complicated case: lost of molar, root treated teeth etc',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P17',
        state: '',
    },
    {
        code: '8.4',
        title: 'Traditional ceramic braces - Simple case: no extraction required',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P17',
        state: '',
    },
    {
        code: '8.5',
        title: 'Traditional ceramic braces - Requires extraction (fee for extraction is not included',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P17',
        state: '',
    },
    {
        code: '8.6',
        title: 'Traditional ceramic braces - Complicated case: lost of molar, root treated teeth etc',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P17',
        state: '',
    },
    {
        code: '8.7',
        title: 'Invisalign ClinCheck',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P17',
        state: '',
    },
    {
        code: '8.8',
        title: 'Invisalign',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P16',
        state: '',
    },
    {
        code: '8.9',
        title: 'Functional appliance',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P16',
        state: '',
    },
    ],
},
{
    code: '9',
    title: 'Surgey',
    codes: [{
        code: '9.1',
        title: 'Permanent tooth extraction',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P18',
        state: '',
    },
    {
        code: '9.2',
        title: 'Wisdom tooth extraction (upper jaw)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P18',
        state: '',
    },
    {
        code: '9.3',
        title: 'Wisdom tooth extraction (lower jaw)',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P18',
        state: '',
    },
    {
        code: '9.4',
        title: 'Surgical tooth extraction',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P18',
        state: '',
    },
    {
        code: '9.5',
        title: 'Tooth extraction with bone grafting',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P19',
        state: '',
    },
    {
        code: '9.6',
        title: 'Crown lengthening surgery',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P20',
        state: '',
    },
    {
        code: '9.7',
        title: 'Gum contouring surgery',
        description: '',
        price: 12,
        available: true,
        templateCode: 'P20',
        state: '',
    },
    ],
},
];
