export default {
    codes: {
        ServerErrorCode: -32000,
        InvalidParamsErrorCode: -32602,
        InvalidTokenErrorCode: 32101,
        LoginErrorCode: 32102,
        InvalidOrganizationErrorCode: 32103,
        PatientNotFoundErrorCode: 32104,
    },
    messages: {
        InvalidLoginErrorMessage: 'invalid login',
        WrongPasswordErrorMessage: 'wrong password',
        InvalidOrganizationErrorMessage: 'invalid organization',
        OrganizationIDParamRequiredErrorMessage: 'organizationID param required',
        PatientIDParamRequiredErrorMessage: 'patientID param required',
        planIDParamRequiredErrorMessage: 'planID param required',
        ProcedureIDParamRequiredErrorMessage: 'procedureID param required',
        RefreshTokenParamRequiredErrorMessage: 'refreshToken param required',
        UsernameParamRequiredErrorMessage: 'username param required',
        PasswordParamRequiredErrorMessage: 'password param required',
        FirstNameParamRequiredErrorMessage: 'firstName param required',
        LastNameParamRequiredErrorMessage: 'lastName param required',
        PatientNotFoundErrorMessage: 'patient not found',
    },
};
