import toggleLocation from './toggle-location';
import setOnlyOneLocation from './set-only-one-location';
import toggleAllLocations from './toggle-all-locations';
import setOnlyOneLocationPlusFalse from './set-only-one-location-plus-false';

export default [
	{
		code: 'K00',
		title: 'Нарушения развития и прорезывания зубов',
		codes: [
			{
				code: 'K00.0',
				title: 'Адентия',
				explain: 'Congenitally missing teeth - complete or partial',
				toggleAll: true,
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					root: false,
					coronaLingual: false,
					coronaLabial: false,
					coronaTop: false,
				},
				locations: {
					root: false,
					coronaLingual: false,
					coronaLabial: false,
					coronaTop: false,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K00.1',
				title: 'Сверхкомплектные зубы',
				explain: 'Mesiodens',
				setOnLoad: { background: true },
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K00.2',
				title: 'Отклонения от размера и формы зуба',
				explain:
					'Macr/micro-dontia, dens in dente, cocrescence, fusion, gemination, peg',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K00.3',
				title: 'Крапчатые  зубы',
				explain: 'Fluorosis',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
			},
			{
				code: 'K00.4',
				title: 'Нарушение формирования зубов',
				explain: 'Enamel hypoplasia, dilaceration, Turner',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K00.5',
				title: 'Наследственные нарушения структуры зуба',
				setOnLoad: {},
				explain: 'Amylo/dentino-genisis imperfecta',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K00.6',
				title: 'Нарушения прорезывания зубов',
				setOnLoad: {},
				explain:
					'Natal/neonatal teeth, retained deciduous tooth, premature, late',
				toggleAll: true,
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K00.7',
				title: 'Синдром прорезывания зубов',
				setOnLoad: {},
				toggleAll: true,
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K00.8',
				title: 'Другие нарушения развития зубов',
				setOnLoad: {},
				explain:
					'Colour changes due to blood incompatability, biliary, porphyria, tetyracy',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					root: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
			},
			{
				code: 'K00.9',
				title: 'Нарушение развития зубов неуточненные',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					root: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
			},
		],
	},

	{
		code: 'K01',
		title: 'Ретенированные и импактные зубы',
		codes: [
			{
				code: 'K01.0',
				title: 'Ретенированные зубы',
				setOnLoad: {},
				explain: 'Distinguish from impacted tooth',
				locations: {},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K01.1',
				title: 'Импактные зубы',
				setOnLoad: {},
				explain: 'In contact with another tooth',
				locations: {},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
		],
	},
	{
		code: 'K02',
		title: 'Кариес зубов',
		codes: [
			{
				code: 'K02.0',
				title: 'Кариес эмали стадия белого (мелового) пятна',
				setOnLoad: {},
				explain: 'Restoration, amalgam, composite, resin',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
					periodontit: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					periodontit: true,
					rootCanal: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K02.1',
				title: 'Кариес дентина',
				setOnLoad: {},
				explain: 'Restoration, amalgam, composite, resin',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
					periodontit: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					periodontit: true,
					rootCanal: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K02.2',
				title: 'Кариес цемента',
				setOnLoad: {},
				explain: 'Restoration, amalgam, composite, resin, crown',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
					periodontit: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					periodontit: true,
					rootCanal: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K02.3',
				title: 'Приостановившийся кариес зубов',
				setOnLoad: {},
				explain: 'Restoration, amalgam, composite, resin, crown',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
					periodontit: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					periodontit: true,
					rootCanal: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K02.4',
				title: 'Одонтоклазия детская меланодентия, меланодонтоклазия',
				explain: 'Infantile meladontia',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
					periodontit: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					periodontit: true,
					rootCanal: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K02.8',
				title: 'Другой уточненный кариес зубов',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
					periodontit: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					periodontit: true,
					rootCanal: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K02.9',
				title: 'Кариес зубов неуточненный',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
					periodontit: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					periodontit: true,
					rootCanal: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
		],
	},
	{
		code: 'K03',
		title: 'Другие болезни твердых тканей зубов',
		codes: [
			{
				code: 'K03.0',
				title: 'Повышенное стирание зубов',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K03.1',
				title: 'Сошлифовывание (абразивный знос) зубов',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K03.2',
				title: 'Эрозия зубов',
				explain: 'Vomiting, anorexia, bulhemia, acid, diet',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K03.3',
				title: 'Патологическая резорбция зубов',
				explain: 'Pink spot',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					root: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K03.4',
				title: 'Гиперцементоз',
				setOnLoad: { root: true },
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					root: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K03.5',
				title: 'Анкилоз зубов',
				explain: 'Pink spot',
				setOnLoad: { root: true },
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					root: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K03.6',
				title: 'Отложения (наросты) на зубах',
				explain:
					'Pigmentation, tobacco, betel, plaque, calculus, scaling and polishing',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K03.7',
				title: 'Изменения цвета твердых тканей зубов после прорезывания',
				explain: 'Metal, pulpal bleeding, betel, tobacco',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K03.8',
				title: 'Другие  уточненные болезни твердых тканей зубов',
				explain: 'Sensitive dentine',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K03.9',
				title: 'Болезнь твердых тканей зубов неуточненная',
				explain: '',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
		],
	},
	{
		code: 'K04',
		title: 'Болезни пульпы и периапикальных тканей',
		codes: [
			{
				code: 'K04.0',
				title: 'Пульпит',
				explain:
					'Pulp cap, root canal treatment,sedative dressing, endodontic,obturate',
				setOnLoad: { rootCanal: true },
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
				},
				view: {
					root: true,
					rootCanal: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K04.1',
				title: 'Некроз пульпы (гангрена пульпы)',
				explain:
					'Gangrene, root canal treatment,sedative dressing, endodontic,obturate',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
				},
				view: {
					root: true,
					rootCanal: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K04.2',
				title: 'Дегенерация пульпы дентикли, пульпарные камни',
				explain: 'Pulp stones, sclerosis',
				setOnLoad: { rootCanal: true },
				locations: {
					rootCanal: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
			},
			{
				code: 'K04.3',
				title: 'Неправильное формирование твердых тканей в пульпе',
				explain: '2ndary dentine - excludes pulp stones(K04.2)',
				setOnLoad: { rootCanal: true },
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
				},
				view: {
					root: true,
					rootCanal: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K04.4',
				title: 'Острый апикальный периодонтит пульпарного происхождения ',
				explain: 'Root canal treatment,endodontic,obturate, abcess',
				setOnLoad: {
					rootCanal: true,
					periodontit: true,
				},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
					periodontit: true,
				},
				view: {
					periodontit: true,
					root: true,
					rootCanal: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K04.5',
				title: 'Хронический апикальный периодонтит (апикальная гранулема)',
				explain: 'Granuloma, root canal treatment,endodontic,obturate,abcess',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					rootCanal: true,
					periodontit: true,
				},
				locations: {
					rootCanal: true,
					periodontit: true,
				},
				view: {
					periodontit: true,
					root: true,
					rootCanal: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K04.6',
				title: 'Периапикальный абсцесс со свищем  ',
				explain: 'Root canal treatment,endodontic,obturate,abcess',

				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					rootCanal: true,
					periodontit: true,
				},
				locations: {
					rootCanal: true,
					periodontit: true,
				},
				view: {
					periodontit: true,
					root: true,
					rootCanal: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K04.7',
				title: 'Периапикальный абсцесс без свища',
				explain: 'Root canal treatment,endodontic,obturate,abcess',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					rootCanal: true,
					periodontit: true,
				},
				locations: {
					rootCanal: true,
					periodontit: true,
				},
				view: {
					periodontit: true,
					root: true,
					rootCanal: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K04.8',
				title: 'Корневая киста ',
				explain: 'Apical cyst, enucleate,apicectomy, apicoectomy',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					rootCanal: true,
					periodontit: true,
				},
				locations: {
					rootCanal: true,
					periodontit: true,
				},
				view: {
					periodontit: true,
					root: true,
					rootCanal: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K04.9',
				title: 'Другие неуточненные болезни пульпы и периапикальных тканей',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					rootCanal: true,
					periodontit: true,
				},
				locations: {
					rootCanal: true,
					periodontit: true,
				},
				view: {
					periodontit: true,
					root: true,
					rootCanal: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
		],
	},
	{
		code: 'K05',
		title: 'Гингивит и болезни пародонта',
		codes: [
			{
				code: 'K05.0',
				title: 'Острый гингивит',
				explain: 'Gingivitis, bleeding gums, scaling',
				addLocation: (location, diagnose, originalDiagnose, toothId) => setOnlyOneLocationPlusFalse(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
					gum: false,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: false,
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
				},
			},
			{
				code: 'K05.1',
				title: 'Хронический гингивит',
				explain:
					'Gingivitis, bleeding gums, scaling, ulcerative - excludes Vincent',
				addLocation: (location, diagnose, originalDiagnose, toothId) => setOnlyOneLocationPlusFalse(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
					gum: false,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: false,
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
				},
			},
			{
				code: 'K05.2',
				title: 'Острый парадонтит',
				explain: 'Gingivitis, bleeding gums, scaling ',
				addLocation: (location, diagnose, originalDiagnose, toothId) => setOnlyOneLocationPlusFalse(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
					gum: false,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
				},
			},
			{
				code: 'K05.3',
				title: 'Хронический пародонтит',
				explain: 'Gingivitis, chronic pericoronitis, bleeding gums, scaling',
				addLocation: (location, diagnose, originalDiagnose, toothId) => setOnlyOneLocationPlusFalse(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
					gum: false,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: false,
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
				},
			},
			{
				code: 'K05.4',
				title: 'Пародонтоз',
				explain: 'Juvenile,gingivitis, bleeding gums, scaling, curettage',
				addLocation: (location, diagnose, originalDiagnose, toothId) => setOnlyOneLocationPlusFalse(location, diagnose, originalDiagnose, toothId),
				locations: {
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
					gum: false,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: false,
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
				},
			},
			{
				code: 'K05.5',
				title: 'Другие болезни пародонта',
				explain: 'Gingivitis, bleeding gums, scaling',
				addLocation: (location, diagnose, originalDiagnose, toothId) => setOnlyOneLocationPlusFalse(location, diagnose, originalDiagnose, toothId),
				locations: {
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
					gum: false,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: false,
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
				},
			},
			{
				code: 'K05.6',
				title: 'Другие болезни пародонта, неуточненные',
				addLocation: (location, diagnose, originalDiagnose, toothId) => setOnlyOneLocationPlusFalse(location, diagnose, originalDiagnose, toothId),
				locations: {
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
					gum: false,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: false,
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
				},
			},
		],
	},
	{
		code: 'K06',
		title: 'Другие изменения десны и беззубого альвеолярного края',
		codes: [
			{
				addLocation: (location, diagnose, originalDiagnose, toothId) => setOnlyOneLocationPlusFalse(location, diagnose, originalDiagnose, toothId),
				code: 'K06.0',
				title: 'Рецессия десны',
				explain: 'Gingiva, recession',
				setOnLoad: {
				},
				locations: {
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
					gum: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: false,
					paradontit1: true,
					paradontit2: true,
					paradontit3: true,
					paradontit4: true,
				},
			},
			{
				code: 'K06.1',
				title: 'Гипертрофия десны',
				explain: 'Fibromatosis',
				toggleAll: true,
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					gum: true,
				},
				locations: {
					gum: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K06.2',
				title:
					'Поражения десны и беззубого альвеолярного края, обусловленные травмой',
				explain: 'Denture hyperplasia occlusion, toothbrushing',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					gum: true,
				},
				locations: {
					gum: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K06.8',
				title:
					'Другие уточненные изменения десны и беззубого альвеолярного края',
				explain: 'Gingival cyst, epulis, pyogenic granuloma',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					gum: true,
				},
				locations: {
					gum: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K06.9',
				title: 'Изменения десны и беззубого альвеолярного края неуточненные',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					gum: true,
				},
				locations: {
					gum: false,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
		],
	},
	{
		code: 'K07',
		title: 'Челюстно-лицевые аномалии (включая аномалии прикуса)',
		codes: [
			{
				code: 'K07.0',
				title: 'Основные аномалии размеров челюстей',
				explain: 'Gingiva, recession',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K07.1',
				title: 'Аномалии челюстно-черепных соотношений',
				explain:
					'Asymetry, pro/retrognathic, Cl 2, Cl 3, osteotomy, orthognathic, ortho',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K07.2',
				title: 'Аномалии соотношения зубных дуг',
				explain:
					'Overjet, overbite, crossbite,midline deviation, orthodontic, banding',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K07.3',
				title: 'Аномалии положения зубов',
				explain: 'Crowding, rotation, distema, transposition',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K07.4',
				title: 'Аномалии прикуса неуточненные',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K07.5',
				title: 'Челюстно-лицевые аномалии функционального происхождения',
				explain: 'Mouth breathing, abnormal swallowing, habits',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K07.6',
				title: 'Болезни ВЧНС',
				explain: 'Dislocation, TMJ, click, pain',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K07.8',
				title: 'Другие денто-лицевые аномалии',
				explain: 'Dislocation, TMJ, click, pain',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K07.9',
				title: 'Денто-лицевая аномалия, неуточненная',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
		],
	},
	{
		code: 'K08',
		title: 'Другие изменения зубов и их опорного аппарата',
		codes: [
			{
				code: 'K08.0',
				title: 'Эксфолиация зубов из-за системных нарушений',
				explain: 'Hypophosphatasia, scurvy',
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K08.1',
				title:
					'Потеря зубов вследствие несчастного случая, удаления или локализованного пародонтита',
				explain: 'Denture, bridge, implant, space maintainer',
				toggleAll: true,
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					root: false,
					coronaLingual: false,
					coronaLabial: false,
					coronaTop: false,
				},
				locations: {
					root: false,
					coronaLingual: false,
					coronaLabial: false,
					coronaTop: false,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K08.2',
				title: 'Атрофия беззубого альвеолярного края',
				explain: 'Gingival mucosal graft',
				toggleAll: true,
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					root: false,
					coronaLingual: false,
					coronaLabial: false,
					coronaTop: false,
					gum: true,
				},
				locations: {
					root: false,
					coronaLingual: false,
					coronaLabial: false,
					coronaTop: false,
					gum: true,
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K08.3',
				title: 'Оставшийся корень зуба',
				explain: 'Root rest',
				toggleAll: true,
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					root: undefined,
					coronaLingual: false,
					coronaLabial: false,
					coronaTop: false,
				},
				locations: {
					root: undefined,
					coronaLingual: false,
					coronaLabial: false,
					coronaTop: false,
				},
				view: {
					root: true,
					coronaLingual: false,
					coronaLabial: false,
					coronaTop: false,
					gum: true,
				},
			},
			{
				code: 'K08.8',
				title: 'Другие уточненные изменения зубов и их опорного аппарата',
				explain: 'Toothache NOS',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
					periodontit: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					periodontit: true,
					rootCanal: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
			{
				code: 'K08.9',
				title: 'Изменения зубов и их опорного аппарата неуточненное',
				setOnLoad: {},
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleLocation(location, diagnose, originalDiagnose, toothId),
				locations: {
					rootCanal: true,
					periodontit: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
				},
				view: {
					coronaLingual: true,
					periodontit: true,
					rootCanal: true,
					coronaLingualIncisalDistal: true,
					coronaLingualIncisalMiddle: true,
					coronaLingualIncisionMesial: true,
					coronaLingualMiddleDistal: true,
					coronaLingualMiddleMiddle: true,
					coronaLingualMiddleMesial: true,
					coronaLingualCervicalDistal: true,
					coronaLingualCervicalMiddle: true,
					coronaLingualCervicalMesial: true,
					coronaLabial: true,
					coronaLabialIncisalDistal: true,
					coronaLabialIncisalMiddle: true,
					coronaLabialIncisionMesial: true,
					coronaLabialMiddleDistal: true,
					coronaLabialMiddleMiddle: true,
					coronaLabialMiddleMesial: true,
					coronaLabialCervicalDistal: true,
					coronaLabialCervicalMiddle: true,
					coronaLabialCervicalMesial: true,
					coronaTopBuccal: true,
					coronaTopMedial: true,
					coronaTopLingual: true,
					coronaTopDistal: true,
					coronaTopOclusial: true,
					root: true,
					gum: true,
				},
			},
		],
	},
	{
		code: 'K09',
		title: 'Кисты области рта, не классифицированные в других  рубриках',
		codes: [
			{
				code: 'K09.0',
				title: 'Киста при прорезывании зубов',
				explain:
					'cyst, eruption, gingival, Kerato, dentigerous,lateral periodontal',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K09.1',
				title: 'Ростовые (неодонтогенные) кисты области рта',
				explain: 'Nasopalatine cyst',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K09.2',
				title: 'Другие кисты челюстей',
				explain: 'Nasopalatine cyst',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K09.8',
				title: 'Кисты полости рта, не классифицированные в других рубриках',
				explain: 'Dermoid cyst',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K09.9',
				title: 'Кисты полости рта, неуточненные',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
		],
	},
	{
		code: 'K10',
		title: 'Другие болезни челюстей',
		codes: [
			{
				code: 'K10.0',
				title: 'Нарушения развития челюстей',
				explain: 'Tori',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K10.1',
				title: 'Гигантоклеточная гранулема центральная',
				explain: '',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K10.2',
				title: 'Воспалительные заболевания челюстей',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K10.3',
				title: 'Альвеолит челюстей альвеолярный остеит, сухая лунка',
				explain: 'Osteomyelitis, sequestra',
				toggleAll: true,
				addLocation: (location, diagnose, originalDiagnose, toothId) => toggleAllLocations(location, diagnose, originalDiagnose, toothId),
				setOnLoad: {
					root: true,
					coronaLingual: false,
					coronaLabial: false,
					coronaTop: false,
				},
				locations: {
					root: true,
					coronaLingual: false,
					coronaLabial: false,
					coronaTop: false,
				},
				view: {
					root: true,
					gum: true,
				},
			},
			{
				code: 'K10.8',
				title: 'Другие уточненные болезни челюстей',
				explain: 'Dry socket',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K10.9',
				title: 'Болезнь челюстей неуточненная',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
		],
	},
	{
		code: 'K11',
		title: '<олезни слюнных желез',
		codes: [
			{
				code: 'K11.0',
				title: 'Атрофия слюнной железы',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K11.1',
				title: 'Гипертрофия слюнной железы',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K11.2',
				title: 'Сиалоадеит',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K11.3',
				title: 'Абсцесс слюнной железы',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K11.4',
				title: 'Свищ слюнной железы',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K11.5',
				title: 'Сиалолитиаз, камни в слюнном протоке',
				explain: 'Salivary calculus, stone',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K11.6',
				title: 'Мукоцеле слюнной железы, ранула',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K11.7',
				title: 'Нарушение секреции слюнных желез',
				explain: 'Xerostoma, dry mouth',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K11.8',
				title: 'Другие болезни слюнных желез',
				explain: 'Miculicz',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K11.9',
				title: 'Заболевание слюнной железы неуточненное',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
		],
	},
	{
		code: 'K12',
		title: 'Стоматит и родственные поражения',
		codes: [
			{
				code: 'K12.0',
				title: 'Рецидивирующие афты полости рта',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K12.1',
				title: 'Другие формы стоматита',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K12.2',
				title: 'Флегмона и абсцесс области рта',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
		],
	},
	{
		code: 'K13',
		title: 'Другие болезни губ и слизистой оболочки полости рта',
		codes: [
			{
				code: 'K13.0',
				title: 'Болезни губ',
				explain: 'Angular chelitis',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K13.1',
				title: 'Прикусывание щеки и губ',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K13.2',
				title:
					'Лейкоплакия и другие изменения  эпителия  полости рта, включая язык',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K13.3',
				title: 'Волосатая лейкоплакия',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K13.4',
				title: 'Гранулема и гранулемоподобные поражения слизистой оболочки полости рта',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K13.5',
				title: 'Подслизистый фиброз полости рта',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K13.6',
				title: 'Гиперплазия СОПР вследствие раздражения',
				setOnLoad: {
				},
				locations: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
			{
				code: 'K13.7',
				title: 'Другие и неуточненные поражения слизистой оболочки полости рта',
				setOnLoad: {
				},
				view: {
					root: true,
					coronaLingual: true,
					coronaLabial: true,
					coronaTop: true,
					gum: true,
				},
			},
		],
	},
	{
		code: 'K14',
		title: 'Болезни языка',
		codes: [
			{
				code: 'K14.0',
				title: 'Глоссит',
				explain: 'Ulcer, abscess',
			},
			{
				code: 'K14.1',
				title: 'Географический язык, эксфолиативный глоссит',
			},
			{
				code: 'K14.2',
				title: 'Срединный ромбовидный глоссит',
			},
			{
				code: 'K14.3',
				title: 'Гипертрофия сосочков языка',
				explain: 'Black hairy tongue',
			},
			{
				code: 'K14.4',
				title: 'Атрофия сосочков языка',
			},
			{
				code: 'K14.5',
				title: 'Складчатый, морщинистый, бороздчатый, расщепленный язык',
				explain: 'Scrotal, fissured tongue',
			},
			{
				code: 'K14.6',
				title: 'Глоссодиния',
			},
			{
				code: 'K14.8',
				title: 'Глоссодиния неуточненная',
			},
			{
				code: 'K14.9',
				title: 'Болезнь языка неуточненная',
			},
		],
	},
];
