export default [{
        categoryCode: '1.1.',
        categoryTitle: 'Stomatologic examination and procedures',
        code: '1.1.1.',
        title: 'Stomatologic inspection at primary address',
        price: '6,54',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.1.',
        categoryTitle: 'Stomatologic examination and procedures',
        code: '1.1.2.',
        title: 'Dynamic supervision in the course of treatment',
        price: '3,27',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.1.',
        categoryTitle: 'Stomatologic examination and procedures',
        code: '1.1.3.',
        title: 'Stomatologic inspection with issue of the advisory opinion:',
        price: '9,81',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.1.',
        categoryTitle: 'Stomatologic examination and procedures',
        code: '1.1.4.',
        title: 'Analysis of dental pictures',
        price: '1,64',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.1.',
        categoryTitle: 'Stomatologic examination and procedures',
        code: '1.1.5.',
        title: 'Analysis of viziogram, panoramic roentgenograms, orthopantomogram, teleroentgenograms',
        price: '4,91',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.1.',
        categoryTitle: 'Stomatologic examination and procedures',
        code: '1.1.6.',
        title: 'Analysis of results of additional methods of research',
        price: '1,64',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.2.',
        categoryTitle: 'Professional hygiene',
        code: '1.2.1.',
        title: 'Motivation on risk factors of stomatologic diseases, training of the patient in toothbrushing',
        price: '3,27',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.2.',
        categoryTitle: 'Professional hygiene',
        code: '1.2.2.',
        title: 'Covering of one tooth with the fluorinated or pressurizing preparation',
        price: '1,39',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.2.',
        categoryTitle: 'Professional hygiene',
        code: '1.2.3.',
        title: 'Covering of the subsequent tooth with the fluorinated or pressurizing preparation',
        price: '1,06',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.2.',
        categoryTitle: 'Professional hygiene',
        code: '1.2.4.',
        title: 'Control of hygiene with application of special indexes in key teeth',
        price: '2,62',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.2.',
        categoryTitle: 'Professional hygiene',
        code: '1.2.6.',
        title: 'Removal of a dental plaque from one tooth, cleaning of tooth',
        price: '1,23',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.2.',
        categoryTitle: 'Professional hygiene',
        code: '1.2.9.',
        title: 'Removal of tooth deposits with an ultrasonic skeyler from one tooth',
        price: '1,31',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.2.',
        categoryTitle: 'Professional hygiene',
        code: '1.2.13.',
        title: 'Polishing of one tooth after removal of tooth deposits',
        price: '1,76',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.3.',
        categoryTitle: 'Anaesthetic help',
        code: '1.3.1.',
        title: 'Application anesthesia',
        price: '1,79',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.3.',
        categoryTitle: 'Anaesthetic help',
        code: '1.3.2.',
        title: 'Infiltration anesthesia',
        price: '3,27',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.3.',
        categoryTitle: 'Anaesthetic help',
        code: '1.3.3.',
        title: 'Conduction anesthesia',
        price: '4,91',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.3.',
        categoryTitle: 'Anaesthetic help',
        code: '1.3.4.',
        title: 'Intraligamentarny anesthesia',
        price: '3,27',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.3.',
        categoryTitle: 'Anaesthetic help',
        code: '1.3.5.',
        title: 'Application of a disposable syringe with a needle',
        price: '0,13',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.3.',
        categoryTitle: 'Anaesthetic help',
        code: '1.3.6.',
        title: 'Application of a karpulny syringe with a needle',
        price: '0,08',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.3.',
        categoryTitle: 'Anaesthetic help',
        code: '1.3.8.',
        title: 'Use of anesthetic',
        price: '0,49',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.1.',
        title: 'Imposing of a temporary seal of DENTIV',
        price: '1,66',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.1.',
        title: 'Imposing of a temporary seal of SEPTOPAK',
        price: '1,82',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.1.',
        title: 'Imposing of a temporary seal of PARASEPT',
        price: '1,67',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.2.',
        title: 'Removal of one strongly fixed seal',
        price: '5,33',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.3.',
        title: 'Removal of one defective seal',
        price: '3,02',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.7.',
        title: 'Instillation (irrigation) of an oral cavity with an anti-septic tank',
        price: '1,05',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.8.',
        title: 'Retraktion of a gum of one tooth',
        price: '1,06',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.9.',
        title: 'Application of styptic means',
        price: '1,04',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.13.',
        title: 'Coagulation of a hypertrophied gingival papilla',
        price: '1,31',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.14.',
        title: 'Local medicinal processing of the centers of defeat of a mucous membrane of an oral cavity',
        price: '4,91',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.27.',
        title: 'Sampling of material for cytologic research',
        price: '4,99',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.28.',
        title: 'Sampling of material  for microbiological research',
        price: '4,92',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.4.',
        categoryTitle: 'Other general stomatologic actions',
        code: '1.4.29.',
        title: 'Sampling of material  for histologic research (biopsy)',
        price: '6,84',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.1.',
        title: 'Application of a tool kit, used at each visit of the patient on therapeutic reception',
        price: '0,03',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.2.',
        title: 'Application of a tool kit used at each visit of the patient on surgical reception',
        price: '0,03',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.5.',
        title: 'Application of a napkin for the patient disposable',
        price: '0,06',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.6.',
        title: 'Application of a tip on salva ejector mechanism the disposable',
        price: '0,04',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.8.',
        title: 'Application of a mask disposable',
        price: '0,02',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.9.',
        title: 'Application of pair of gloves medical',
        price: '0,31',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.11.',
        title: 'Use of rollers stomatologic',
        price: '0,01',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.12.',
        title: 'Application of gauze balls',
        price: '0,00',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.13.',
        title: 'Use of cotton wool',
        price: '0,01',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.14.',
        title: 'Use of scissors surgical',
        price: '0,03',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.15.',
        title: 'Application of a knife spear-shaped',
        price: '0,01',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.16.',
        title: 'Application chisel of the surgical',
        price: '0,01',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.17.',
        title: 'Application of a probe',
        price: '0,00',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.18.',
        title: 'Application of a scalpel disposable',
        price: '0,07',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.19.',
        title: 'Application of an elevator of the extraction surgical',
        price: '0,05',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.20.',
        title: 'Use of bandage',
        price: '0,59',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.21.',
        title: 'Use of adhesive (one tooth)',
        price: '0,59',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.30.',
        title: 'Use of gel for etching',
        price: '0,05',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.30.1.',
        title: "\"Alyumogel's\" application",
        price: '0,07',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.31.',
        title: 'Use of the powder "Alvanes"',
        price: '0,04',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.31.',
        title: 'Use of Alvanes paste',
        price: '0,02',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.32.',
        title: 'Application strips',
        price: '0,09',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.33.',
        title: 'Application of a disk polishing',
        price: '0,34',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.34.',
        title: 'Application of a spoon kyuretazhny',
        price: '0,00',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.35.',
        title: 'Application of a sutural material',
        price: '2,17',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '1.5.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used at visit of the patient on all types of stomatologic treatment',
        code: '1.5.36.',
        title: 'Application of a compress of haemo static and antiseptic "Alvostaz-gubka"',
        price: '0,50',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.2.',
        categoryTitle: 'Preparation of firm tissues of one tooth at caries treatment (I, II, III, IV, V classes on Bleka) and not carious diseases which have arisen after a teething with localization of cavities irrespective of a surface:',
        code: '2.2.1.',
        title: 'Minimum invasive preparation of a carious cavity',
        price: '3,47',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.2.',
        categoryTitle: 'Preparation of firm tissues of one tooth at caries treatment (I, II, III, IV, V classes on Bleka) and not carious diseases which have arisen after a teething with localization of cavities irrespective of a surface:',
        code: '2.2.2.',
        title: 'Preparation of a carious cavity at destruction to 1/3 crowns of tooth',
        price: '4,98',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.2.',
        categoryTitle: 'Preparation of firm tissues of one tooth at caries treatment (I, II, III, IV, V classes on Bleka) and not carious diseases which have arisen after a teething with localization of cavities irrespective of a surface:',
        code: '2.2.3.',
        title: 'Preparation of a carious cavity at destruction to 1/2 crowns of tooth',
        price: '7,30',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.2.',
        categoryTitle: 'Preparation of firm tissues of one tooth at caries treatment (I, II, III, IV, V classes on Bleka) and not carious diseases which have arisen after a teething with localization of cavities irrespective of a surface:',
        code: '2.2.4.',
        title: 'Preparation of a carious cavity at destruction more than 1/2 crowns of tooth',
        price: '9,64',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.3.',
        categoryTitle: 'Production of the isolating laying',
        code: '2.3.1.',
        title: 'Production of the containing laying isolating cement',
        price: '2,90',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.3.',
        categoryTitle: 'Production of the isolating laying',
        code: '2.3.2.',
        title: 'Production of the isolating laying from glass ionomeric cement VITREMER',
        price: '5,45',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.3.',
        categoryTitle: 'Production of the isolating laying',
        code: '2.3.2.',
        title: 'Production of the isolating laying from glass ionomeric ionomeric cementKETAK',
        price: '3,55',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.3.',
        categoryTitle: 'Production of the isolating laying',
        code: '2.3.2.',
        title: 'Production of the isolating laying from glass ionomeric cement (fluid) FILTEK',
        price: '6,33',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.3.',
        categoryTitle: 'Production of the isolating laying',
        code: '2.3.3.',
        title: 'Production isolating a photo cured (a composite, a kompomer, to a flo) laying',
        price: '3,34',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.3.',
        categoryTitle: 'Production of the isolating laying',
        code: '2.3.5.',
        title: 'Production calcium of the containing medical laying',
        price: '2,65',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.1.',
        title: 'Preparation of a carious cavity and cavity of single-root tooth',
        price: '5,54',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.2.',
        title: 'Preparation of a carious cavity and cavity of multiroot tooth',
        price: '8,00',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.3.',
        title: 'Imposing of devitalizing paste',
        price: '2,03',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.4.',
        title: 'Tool processing of one well passable channel',
        price: '4,17',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.5.',
        title: 'Tool processing of one badly passable channel',
        price: '8,46',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.8.',
        title: 'Pulp amputation',
        price: '0,98',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.10.',
        title: 'Pulp extirpation from one channel',
        price: '1,91',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.11.',
        title: 'Rasplombirovaniye and tool processing of one channel of the tooth which has been earlier sealed up with paste',
        price: '7,73',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.12.',
        title: 'Rasplombirovaniye and tool processing of one channel of the tooth which has been earlier sealed up with cement, rezortsinformalinovy paste',
        price: '11,38',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.15.',
        title: 'Antiseptic processing of one channel',
        price: '1,64',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.16.',
        title: 'Medicamentous processing of one channel by means of special means for passing and expansion of the root channel',
        price: '4,31',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.17.',
        title: 'Medical intra channel bandage of one channel',
        price: '3,39',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.20.',
        title: 'Sealing of one channel with paste (siller)',
        price: '6,33',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.21.',
        title: 'Sealing of one channel with gutta-percha pins on a siller a condensation method',
        price: '6,94',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.4.',
        categoryTitle: 'Endodontal treatment of one tooth at a pulpitis and apical periodontitis',
        code: '2.4.23.',
        title: 'Measurement of length of the channel by means of the device "Apekslokator"',
        price: '2,62',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.5.',
        title: 'Restoration of coronal  part of one tooth with a light curing composite material at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface at the minimum invasive preparation of a carious cavity (a material sealing, a bonding, FILTEK accessories a set)',
        price: '8,00',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.6.',
        title: 'Restoration of coronal part of one tooth with a light  composite material at treatment of a carious cavity of I, II, III, IV, V classes on Blek with localization of cavities irrespective of a surface of a carious cavity at destruction to 1/3 crowns of tooth (a material sealing, a bonding, FILTEK accessories a set)',
        price: '10,36',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.7.',
        title: 'Restoration of coronal part of one tooth with a light  composite material at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface of a carious cavity at destruction to 1/2 crowns of tooth (a material sealing, a bonding, FILTEK accessories a set)',
        price: '12,72',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.8.',
        title: 'Restoration ofcoronal part of one tooth with a light  composite material at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface of a carious cavity at destruction more than 1/2 crowns of tooth (a material sealing, a bonding, FILTEK accessories a set)',
        price: '15,09',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.16.',
        title: 'Restoration of coronal part of one tooth with light curing cement at treatment of a carious cavity of I, II, III, IV, V classes by Bleka with localization of cavities irrespective of a surface at the minimum invasive preparation of a carious cavity (a material sealing VITREMER)',
        price: '8,61',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.16.',
        title: 'Restoration of coronal part of one tooth with light curing cement at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface at the minimum invasive preparation of a carious cavity (a material sealing KETAK)',
        price: '6,83',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.16.',
        title: 'Restoration of coronal part of one tooth with light curing cement at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface at the minimum invasive preparation of a carious cavity (a material stomatol.restavrats.fluid FILTEK)',
        price: '9,61',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.17.',
        title: 'Restoration of coronal part of one tooth with  light curing cement at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface of a carious cavity at destruction to 1/3 crowns of tooth (a material sealing VITREMER)',
        price: '10,93',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.17.',
        title: 'Restoration of coronal part  of one tooth by light curing cement at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface of a carious cavity at destruction to 1/3 crowns of tooth (a material sealing KETAK)',
        price: '8,56',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.17.',
        title: 'Restoration of coronal part of one tooth by light curing cement at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface of a carious cavity at destruction to 1/3 crowns of tooth (a material stomatol.restavrats.tekuchy FILTEK)',
        price: '12,27',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.18.',
        title: 'Restoration ofcoronal part t of one tooth by light curing cement at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface of a carious cavity at destruction to 1/2 crowns of tooth (a material sealing VITREMER)',
        price: '13,25',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.18.',
        title: 'Restoration of coronal part of one tooth by light curing cement at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface of a carious cavity at destruction to 1/2 crowns of tooth (a material sealing KETAK)',
        price: '10,28',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.18.',
        title: 'Restoration of coronal part of one tooth by light curing cement at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface of a carious cavity at destruction to 1/2 crowns of tooth (a material stomatol.restavrats.tekuchy FILTEK)',
        price: '14,92',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.19.',
        title: 'Restoration of coronal part of one tooth by light curing cement at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface of a carious cavity at destruction more than 1/2 crowns of tooth (a material sealing VITREMER)',
        price: '15,58',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.19.',
        title: 'Restoration of coronal part of one tooth by light curing cement at treatment of a carious cavity of I, II, III, IV, V classes by Blek with localization of cavities irrespective of a surface of a carious cavity at destruction more than 1/2 crowns of tooth (a material sealing KETAK)',
        price: '12,01',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.22.',
        title: 'Restoration of coronal part of tooth with anchor application (an intrapulparny pin) in one channel (without seal cost)',
        price: '8,82',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.23.',
        title: 'Viniringovy (direct) covering of koronkovy part of tooth (without seal cost)',
        price: '7,14',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.24.',
        title: 'Restoration of a corner of koronkovy part of tooth at break off (without seal cost)',
        price: '3,87',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.25.',
        title: 'Restoration of a corner of koronkovy part of tooth at caries and pulpitis treatment (without seal cost)',
        price: '5,51',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.26.',
        title: 'Complete recovery of an anatomic form of koronkovy part of frontal tooth (without seal cost)',
        price: '8,78',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.27.',
        title: 'Complete recovery of an anatomic form of koronkovy part of chewing tooth (without seal cost)',
        price: '10,41',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.28.',
        title: 'Imposing of a matrix (metal)',
        price: '1,37',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.28.',
        title: 'Matrix imposing (for modeling of seals)',
        price: '1,56',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.28.',
        title: 'Matrix imposing (planimetric section)',
        price: '1,62',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.29.',
        title: 'Application of wedges',
        price: '0,03',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.33.',
        title: 'Polishing, seal polishing from a photocured composite material',
        price: '6,11',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.5.',
        categoryTitle: 'Restoration of coronal part of one tooth at treatment of a carious cavity (I, II, III, IV, the V classes by Bleka) with localization of cavities irrespective of a surface',
        code: '2.5.34.',
        title: 'Polishing, seal polishing',
        price: '4,37',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.7.',
        categoryTitle: 'Treatment of diseases of a periodontium',
        code: '2.7.1.',
        title: 'Curettage of periodontal pockets in one tooth',
        price: '3,28',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.7.',
        categoryTitle: 'Treatment of diseases of a periodontium',
        code: '2.7.4.',
        title: 'Protective bandage in the field of one sextant',
        price: '3,34',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.12.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used on therapeutic reception',
        code: '2.12.1.',
        title: 'use of materials according to the applied treatment technique',
        price: '0,03',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '2.12.',
        categoryTitle: 'Use of tools, products and the means of medical appointment used on therapeutic reception',
        code: '2.12.2.',
        title: 'use of tools, products and means of medical appointment according to the applied treatment technique',
        price: '0,01',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.1.',
        title: 'Bandaging of the postoperative patient',
        price: '6,33',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.2.',
        title: 'Carrying out postoperative actions',
        price: '9,48',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.3.',
        title: 'Training of the patient for operation',
        price: '9,48',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.4.',
        title: 'Change of intermaxillary rubber draft',
        price: '6,36',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.5.',
        title: 'Change of an intermaxillary filar ligature on Rauera',
        price: '9,52',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.6.',
        title: 'Removal of tires',
        price: '8,02',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.7.',
        title: 'Removal of seams',
        price: '6,33',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.8.',
        title: 'Suture',
        price: '6,91',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.9.',
        title: 'Imposing of one seam during carrying out operation',
        price: '3,76',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.10.',
        title: 'Operation of removal of single-root tooth by nippers',
        price: '6,33',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.11.',
        title: 'Operation of removal of single-root tooth by nippers and elevator',
        price: '9,48',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.12.',
        title: 'Operation of the extracted single-root tooth by a gouging method with cutting out mucous надкосничного a rag',
        price: '12,63',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.13.',
        title: 'Operation of the extracted single-root tooth by a cutting out method with cutting out mucous надкосничного a rag',
        price: '18,94',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.14.',
        title: 'Operation of removal of multiroot tooth by nippers',
        price: '9,48',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.15.',
        title: 'Operation of removal of multiroot tooth by nippers and elevator',
        price: '12,63',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.16.',
        title: 'Operation of removal of multiroot tooth by a gouging method with cutting out mucous надкосничного rag',
        price: '18,94',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.17.',
        title: 'Operation of removal of multiroot tooth by a cutting out method with cutting out mucous надкосничного rag',
        price: '28,41',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.18.',
        title: 'Operation of removal of retinirovanny tooth',
        price: '18,94',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.19.',
        title: 'Operation of the complicated removal of retenirovanny tooth',
        price: '28,41',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.20.',
        title: 'Operation of removal of one second tooth of the third degree of mobility or one milk tooth',
        price: '4,74',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.21.',
        title: 'Introduction of medicines in a hole of the extracted tooth',
        price: '2,53',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.22.',
        title: 'Stop of lunochkovy bleeding',
        price: '15,79',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.23.',
        title: 'Bleeding stop in an operational wound',
        price: '6,32',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.24.',
        title: 'Kompaktosteotomiya operation',
        price: '17,37',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.25.',
        title: 'Operation of a resection of a top of a root однокорневогозубав areas of the top jaw',
        price: '20,75',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.26.',
        title: 'Operation of a resection of a top of a root однокорневогозубав areas of the bottom jaw',
        price: '23,90',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.27.',
        title: 'Top jaw operation of amputation of a root of multiroot tooth',
        price: '20,75',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.28.',
        title: 'Bottom jaw operation of koronaro-radikulyarny separation of multiroot tooth',
        price: '11,25',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.29.',
        title: 'Bottom jaw operation of a gemisektion of multiroot tooth',
        price: '20,75',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.30.',
        title: 'Remplantation operation',
        price: '33,20',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.31.',
        title: 'Alveolotomiya of one hole of tooth',
        price: '9,48',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.1.',
        categoryTitle: 'General stomatologic actions (therapeutic, out-patient and surgical, orthopedic, orthodontic)',
        code: '3.1.32.',
        title: 'Correction of a crest of an alveolar shoot in one extracted tooth',
        price: '12,64',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.1.',
        title: 'Removal  atomic formations of jaws complicating prosthetics',
        price: '15,80',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.2.',
        title: 'Excision of surpluses of a mucous membrane of alveolar shoots of jaws (to 5 cm)',
        price: '14,21',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.3.',
        title: 'Plastic lengthening of a bridle of language, lips across Limberg',
        price: '18,95',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.4.',
        title: 'Frenuloplatika according to Popovic',
        price: '12,64',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.5.',
        title: 'Frenuloplastika across Glikman',
        price: '12,64',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.6.',
        title: 'Plasticity of the truncated bridle of language a cross section',
        price: '12,64',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.7.',
        title: 'Endossalny implantation of one implant by two landmark technique (cylindrical, screw, combined, plastinochny). Vvdedeniye of an implant (1 stage).',
        price: '22,10',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.8.',
        title: 'Endossalny implantation of one implant by two landmark technique (cylindrical, screw, combined, plastinochny). Installation of the shaper of a desnevy manzhetka (2 stage).',
        price: '9,48',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.9.',
        title: 'Endossalny implantation of one implant by an one-stage technique',
        price: '22,10',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.10.',
        title: 'Direct endossalny implantation of one implant (cylindrical, screw)',
        price: '25,31',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.11.',
        title: 'Introduction of osteoconductive and barrier membranes at dentalny implantation',
        price: '28,45',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.12.',
        title: 'Introduction of osteoconductive preparations made from аутокрови at dentalny implantation',
        price: '18,97',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.13.',
        title: 'Statement of a head of an implant',
        price: '9,49',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.14.',
        title: 'Increase in an alveolar shoot with use of osteoconductive preparations',
        price: '28,45',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.15.',
        title: 'Increase in an alveolar shoot with use autokostnykh of preparations',
        price: '38,49',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.16.',
        title: 'Raising of a bottom of a maxillary bosom (the closed sine lifting) or a bottom of a gushevidny otverstviye',
        price: '37,87',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.17.',
        title: 'Accumulation of height of an alveolar shoot in the field of a bottom of a maxillary bosom. Operation sine elevator (an open technique)',
        price: '41,89',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.18.',
        title: 'Operation of removal of an implant screw',
        price: '18,96',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.2.',
        categoryTitle: 'Surgical preparation of an oral cavity for prosthetics of a shoot in one extracted tooth',
        code: '3.2.19.',
        title: 'Operation of removal of an implant of platichny',
        price: '28,43',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.3.',
        categoryTitle: 'Surgical methods of treatment of diseases of a marginal periodontium',
        code: '3.3.1.',
        title: 'Scrappy operations of Tseshinskogo-Vidmana-Nejmana (in two teeth)',
        price: '19,36',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.3.',
        categoryTitle: 'Surgical methods of treatment of diseases of a marginal periodontium',
        code: '3.3.2.',
        title: 'Deepenings an oral cavity predveriya (the closed technique) across Artyushevich',
        price: '19,36',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.3.',
        categoryTitle: 'Surgical methods of treatment of diseases of a marginal periodontium',
        code: '3.3.3.',
        title: 'Deepenings oral cavity predveriya (open technique)',
        price: '18,96',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.3.',
        categoryTitle: 'Surgical methods of treatment of diseases of a marginal periodontium',
        code: '3.3.4.',
        title: 'Operation of a gingiviektomiya in one tooth',
        price: '9,50',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.3.',
        categoryTitle: 'Surgical methods of treatment of diseases of a marginal periodontium',
        code: '3.3.5.',
        title: 'Operation of a gingiviektomiya in two teeth',
        price: '18,96',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.3.',
        categoryTitle: 'Surgical methods of treatment of diseases of a marginal periodontium',
        code: '3.3.6.',
        title: 'Imposing of the antiseptic isolating bandage',
        price: '3,16',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.3.',
        categoryTitle: 'Surgical methods of treatment of diseases of a marginal periodontium',
        code: '3.3.7.',
        title: 'Use of osteoconductive materials at operations on a marginal periodontium',
        price: '9,47',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.3.',
        categoryTitle: 'Surgical methods of treatment of diseases of a marginal periodontium',
        code: '3.3.8.',
        title: 'Application of barrier membranes at a marginal periodontium',
        price: '15,78',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.1.',
        title: 'Tsistektomiya operation in one single-root tooth without resection of a top of a root',
        price: '13,06',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.2.',
        title: 'Tsistektomiya operation in one tooth with a resection of a top of a root and its retrograde sealing',
        price: '19,37',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.3.',
        title: 'Tsistektomiya operation in one multiroot tooth without resection of a top of a root',
        price: '14,44',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.4.',
        title: 'Filling of bone cavities with the materials stimulating osteogenesis',
        price: '6,33',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.5.',
        title: 'Removal of papilloma of a mucous membrane of an oral cavity',
        price: '9,48',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.6.',
        title: 'Removal of epulis an alveolar shoot of a jaw without defect replacement',
        price: '9,50',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.7.',
        title: 'Removal of epulis alveolar shoot of a jaw defect szameshcheniye',
        price: '18,96',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.8.',
        title: 'Tsistotomiya of sublingual cyst  in an oral cavity',
        price: '25,26',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.9.',
        title: 'Removal of a retentsionny cyst of small salivary gland, mucous membrane of an oral cavity, lip',
        price: '18,95',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.10.',
        title: 'Removal of atheroma',
        price: '18,95',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.11.',
        title: 'Removal of a lipoma with a diameter up to 3 cm',
        price: '18,95',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.12.',
        title: 'Removal haemangioma in lips, a mucous membrane of an oral cavity, language with a diameter up to 1 cm with plastic replacement of defect',
        price: '18,95',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.13.',
        title: 'Removal of precancer states in lips, a mucous membrane of an oral cavity, language, face skin with plastic replacement of defect',
        price: '18,96',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.4.',
        categoryTitle: 'Treatment of patients with benign tumors and opukholyamipodobny educations in an oral cavity',
        code: '3.4.14.',
        title: 'Excision or coagulation of a hypertrophied interdental nipple',
        price: '4,75',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.5.',
        categoryTitle: 'Inflammatory processes of maxillofacial area',
        code: '3.5.1.',
        title: 'Primary surgical processing of subperiostalny abscess',
        price: '6,33',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.5.',
        categoryTitle: 'Inflammatory processes of maxillofacial area',
        code: '3.5.2.',
        title: 'Primary surgical processing of paradentalny abscess',
        price: '4,75',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.5.',
        categoryTitle: 'Inflammatory processes of maxillofacial area',
        code: '3.5.3.',
        title: 'Perikoronaroektomiya',
        price: '6,33',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.5.',
        categoryTitle: 'Inflammatory processes of maxillofacial area',
        code: '3.5.4.',
        title: 'Perikoronarotomiya',
        price: '3,17',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.5.',
        categoryTitle: 'Inflammatory processes of maxillofacial area',
        code: '3.5.5.',
        title: 'Treatment альвеолита one hole of tooth',
        price: '4,75',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.5.',
        categoryTitle: 'Inflammatory processes of maxillofacial area',
        code: '3.5.6.',
        title: 'Primary surgical processing of abscesses of soft fabrics of maxillofacial area',
        price: '12,64',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.1.',
        title: 'Buzhirovaniye of output channels of big salivary glands',
        price: '9,47',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.2.',
        title: 'Sounding of a channel of big salivary gland',
        price: '7,90',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.3.',
        title: 'Massage and instillation of salivary gland',
        price: '9,47',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.4.',
        title: 'Sialodokhotomiya with removal of a concrement from an output channel of submandibular salivary gland',
        price: '17,40',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.5.',
        title: 'Sekvestrektomiya at chronic limited odontogenny osteomyelitis',
        price: '15,82',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.6.',
        title: 'Primary surgical processing of a trauma of soft tissues of the person and oral cavity without defect of fabrics up to 2 cm in size',
        price: '12,65',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.7.',
        title: 'Primary surgical processing of a trauma of soft tissues of the person and oral cavity with defect of fabric up to 2 cm in size',
        price: '18,96',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.8.',
        title: 'Plastic elimination of perforation of a maxillary bosom',
        price: '18,95',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.9.',
        title: 'Removal of hems in the zone of soft tissues of the person and a mucous membrane of an oral cavity up to 2 cm long',
        price: '17,39',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.10.',
        title: 'Imposing of primary delayed seams on wounds of the person',
        price: '9,48',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.11.',
        title: 'Imposing of the secondary delayed seams on wounds of the person',
        price: '12,64',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.12.',
        title: 'Diagnostic blockade of branches of a trigeminal nerve',
        price: '12,63',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '3.6.',
        categoryTitle: 'Other surgical actions',
        code: '3.6.13.',
        title: 'Diagnostic puncture',
        price: '6,32',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '7.',
        categoryTitle: 'Physical therapy (physiotherapeutic treatment of stomatologic diseases)',
        code: '7.1.',
        title: 'Electric zone of ultrahigh frequencies (UVCh) in a face and a neck',
        price: '0,36',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '7.',
        categoryTitle: 'Physical therapy (physiotherapeutic treatment of stomatologic diseases)',
        code: '7.5.',
        title: 'Ultrasonic therapy',
        price: '2,58',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '7.',
        categoryTitle: 'Physical therapy (physiotherapeutic treatment of stomatologic diseases)',
        code: '7.7.',
        title: 'Electroprocedure microwave "Luch-2" (microwave oven therapy)',
        price: '0,44',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '7.',
        categoryTitle: 'Physical therapy (physiotherapeutic treatment of stomatologic diseases)',
        code: '7.9.',
        title: 'Laser therapy',
        price: '0,42',
        available: true,
        consumables: [],
    },
    {
        categoryCode: '8.',
        categoryTitle: 'Radiological diagnostics (stomatologic)',
        code: '8.1.',
        title: 'X-ray analysis aim',
        price: '8,82',
        available: true,
        consumables: [],
    },
];
